### PR TITLE
Pr/1395

### PR DESCRIPTION
**Pull request by clemente13**

### CODE REVIEW

**Comment by tolot27** [comment]
@clemente13 Please give a more descriptive title and briefly explain what the PR implements.

How does it differ from #1405? At least 8281031 looks quite similar to bb962e2.

**Comment by tolot27** [comment]
@clemente13 You did not answer, yet. Can we close this PR?

@bubbledevteam Will you ever provide a DiaBox datasource?

**Comment by bubbledevteam** [comment]
> @clemente13 You did not answer, yet. Can we close this PR?
> 
> @bubbledevteam Will you ever provide a DiaBox datasource?
> 
> BTW: #1662 also implements 0x08.

Nope, just add 0x08 command for decrypted Libre2/LIbre US 14 days data request and Bubble Mini device support

**Comment by bubbledevteam** [comment]
https://github.com/NightscoutFoundation/xDrip/pull/1662/commits/20466b71b003b19bc2848632a1a8272a582910eb#diff-b268d8a60373fdfde56a375c249ef645ff22329a85932e254887e8896923a914L33

**Comment by tolot27** [comment]
Closing in favor of #1662.

**Pull request closed without merging**
