### PR TITLE
New G7 firmware

### PR DESCRIPTION
**Pull request by Navid200**

### CODE REVIEW

**Comment by jamorham** [comment]
Please provide some rationale for the PR thanks.

**Comment by Navid200** [comment]
There is a new firmware.

**Comment by jamorham** [comment]
Does the new firmware version work correctly with xDrip do we know?

**Comment by Navid200** [comment]
No, I always am worried about asking people to backup database, uninstall xDrip, install my version.  So, I have never provided a personal version.  Do you want me to do that?

**Comment by jamorham** [comment]
No that isn't what I was asking. What I'm asking is whether before we remove the warning for this G7 firmware version whether the user who provided this screenshot is having success with xDrip as is? If they're happy then we remove the warning, if not we investigate further...

**Comment by Navid200** [comment]
xDrip is working as much as it can not recognizing the firmware.  He has readings as I already explained in the other channel.
After this PR is merged, xDrip will recognize the firmware and xDrip will do even better for him.

Please merge this.  We can then talk about the warning.
Again, as I explained in the other channel, I may be misunderstanding you.
Are we abandoning Matrix?

**Review by jamorham — APPROVED** [review]

**Comment by Navid200** [comment]
Thank you

**Pull request merged**
