### PR TITLE
BgGraphBuilder: expand data limit maximum if source exceeds expected rate

### PR DESCRIPTION
**Pull request by Navid200**
This is a copy of the following for wear and pebble.
https://github.com/NightscoutFoundation/xDrip/commit/05668fffe2cf0da7f1a4f3f4a360d224da848300

I have not tested this because I have no Android wear device.

The intent is to fix this: https://github.com/NightscoutFoundation/xDrip/issues/1518#issuecomment-1192239714

### CODE REVIEW

**Comment by jamorham** [comment]
Please update the title of the PR to reflect what it actually does - see my commit for the general wording:

https://github.com/NightscoutFoundation/xDrip/commit/05668fffe2cf0da7f1a4f3f4a360d224da848300

**Comment by Navid200** [comment]
@jamorham Please feel free to edit and change the title if it's not good enough.

**Comment by AidasK** [comment]
Can you create a build for this? I would love to try it out

**Review by jamorham — APPROVED** [review]

**Comment by AidasK** [comment]
Woop! How can I download this build?

**Comment by Navid200** [comment]
@AidasK Please be patient

**Pull request merged**
