### PR TITLE
Fix Sensor Battery Broadcast

### PR DESCRIPTION
**Pull request by Philoul**
Hi,
Proposal to fix broadcast of Sensor Bat Level instead of Phone Bat Level (fix https://github.com/NightscoutFoundation/xDrip/issues/1469)
PR done on Master Branch (I didn't see any "dev" branch...)

Thank's for all your work...

### CODE REVIEW

**Review by tolot27 — COMMENTED** [review]
`PowerStateReceiver.getBatteryLevel()` always returns a positive value, `50` in case of an error. But `BridgeBattery.getBestBridgeBattery()` could return `-1`. Is this caught upstream?

I recommend broadcasting only valid values.

**Comment by Philoul** [comment]
Currently this information is not used in AAPS...
I prepared a PR in  AAPS to add this information in AAPS UI and -1 managed in this PR (used to hide it in AAPS UI for other CGM plugin or for xDrip plugin if invalid value received)

https://github.com/nightscout/AndroidAPS/pull/41

**Comment by Philoul** [comment]
@tolot27 If you prefer, I can modify PR to not broadcast key "Intents.EXTRA_SENSOR_BATTERY" and associated value (-1) in case of invalid value... (I think it's better than broadcast a "default value" like 50 if information is invalid or not available)

In AAPS, I check if this key exists in received bundle from xDrip, so it works too...

**Comment by tolot27** [comment]
> @tolot27 If you prefer, I can modify PR to not broadcast key "Intents.EXTRA_SENSOR_BATTERY" and associated value (-1) in case of invalid value... (I think it's better than broadcast a "default value" like 50 if information is invalid or not available)

Maybe it is a good idea to always broadcast the sensor battery level and if it is invalid or not available, it could be handled upstream.
A value of 50 (used by `PowerStateReceiver.getBatteryLevel()`) is definitively incorrect for the sensor battery level and could not be distingished from real values. Hence, -1 is okay.

And with this PR recommend not to change the implementation of `PowerStateReceiver.getBatteryLevel()`.

**Review by tolot27 — CHANGES_REQUESTED** [review]
Please also change the wear code (`wear/src/main/java/com/eveningoutpost/dexdrip/UtilityModels/BroadcastGlucose.java`).

**Review by tolot27 — APPROVED** [review]

**Comment by Philoul** [comment]
Done,
Note, BridgeBattery class was missing in Wear app, so I add a copy of main APP file
"bridge_battery" preference key is updated by cgm modules of wear app, so I think it should work...

**Comment by tolot27** [comment]
> Done,
> Note, BridgeBattery class was missing in Wear app, so I add a copy of main APP file
> "bridge_battery" preference key is updated by cgm modules of wear app, so I think it should work...

Maybe it is not used in wear but anyway, it is compatible now. 👍

**Review by jamorham — APPROVED** [review]
looks good to me

**Pull request merged**
