### PR TITLE
Keep G6 battery voltage logs for 7 days

### PR DESCRIPTION
**Pull request by Navid200**
This will keep the G6 battery voltage logs for 7 days instead of just one day.

In simplest ways, it's enough to know what the battery voltage is to judge the health of the battery.
But, there are many factors affecting the recorded voltage.  Those include temperature, voltage monitor accuracy, battery production variation, battery production batch, noise at the voltage sample time ...

Keeping the logs for 7 days let's us more confidently judge if the battery is the cause of malfunction or not.

This is what the log looks like now before this PR:

This is what the log looks like after this PR:

So, the log will become teal.

This will be helpful for those who help people use xDrip.  Low battery voltage is one of many factors causing malfunction.  It (having a 7-day period instead of only 1 day) will be very helpful to confirm that with certainty instead of just a possibility.

### CODE REVIEW

**Comment by tolot27** [comment]
Would a `UserError.Log.uel()` be sufficient as well? Its severity is still `>3` and the log entry will be retained for seven days.

**Comment by Navid200** [comment]
As long as it is kept for 7 days, I am OK with it.
But, I checked and alert snooze log is also ueh.  I don't know why a snooze alert is more severe than battery voltage.  Is it?  Does it really matter?

**Comment by Navid200** [comment]
I changed it to uel.  I am testing it.  It will take me a few days to confirm that it really keeps them for 7 days.

**Comment by tolot27** [comment]
It will definitely kept for seven days because the severity of uel is [5](https://github.com/NightscoutFoundation/xDrip/blob/f43d0377467dcbfa968c43a0b776bee838798548/app/src/main/java/com/eveningoutpost/dexdrip/Models/UserError.java#L95) and everything above 3 will be [kept for seven days](https://github.com/NightscoutFoundation/xDrip/blob/f43d0377467dcbfa968c43a0b776bee838798548/app/src/main/java/com/eveningoutpost/dexdrip/Models/UserError.java#L140).

**Comment by Navid200** [comment]
This is what it will look like after a search in the logs:
Screenshot_20220209-161715
  
It will be very useful for users as well as for those helping users.

**Comment by tolot27** [comment]
> This is what it will look like after a search in the logs:

Why do the values not change even after seven days? That's a bit surprising to me.
Nevertheless, it is a good adition.

**Review by tolot27 — APPROVED** [review]
An improvement to the battery monitoring.

**Comment by Navid200** [comment]
Under normal circumstances, the voltages don't change much between days 10 to 90.
Thanks

**Pull request merged**
