### PR TITLE
Medtronic CareLink Follower: add pump status data to integration

### PR DESCRIPTION
**Pull request by sedy89**
The current medtronic carelink integration works pretty good, but I am still missing the data of the pump.
The change in this PR was implemented by @benceszasz but it wasn't part of the Medtronic CareLink Follower (MMConnect for xDrip) #1649 PR.
I am using this code since quite a while and I did not face any problem yet. 
Are there any concerns or could this be taken over?

### CODE REVIEW

**Comment by jamorham** [comment]
@benceszasz can you check this? thanks

**Comment by benceszasz** [comment]
@jamorham I haven't added this function to my PR, because I have made a lot of changes in my PR during the long wait time for the approval: additional functions, additional devices, code cleaning, etc. At some point Matthias asked me not to add more changes, do a code freeze and wait patiently for the merge :) This is was just a simple additional function, nothing big.
Anyhow, you would like me to review this PR?

**Comment by Navid200** [comment]
@benceszasz 
I have 8 open PRs myself.  So, I am not one who can tell you what to do or not to do.
The following is only my personal view.

You submitted the original PR that was merged and added CareLink capability to xDrip.  It is being used now.  
If it needs a change, you are the best person who can make suggestions what it should be.

This does not mean that no one else should make suggestions.  But, you know what you added better than anyone else.
If you believe this PR is the best way to add the intended functionality or to fix a bug, you can state that it is.

On the other hand, if you believe that this added functionality or this fixed bug can be addressed easier, more reliably, less complicated, less power-hungry, ...., you can state that.  In that case, you can either make suggestions to improve this PR.  Or, you can open a different PR to address that.

But, if you open another PR that does that but also adds a lot more, that may not have a better chance of being merged.
It's always best to open incremental PRs to make it clear what it does and make it easier for the reviewer to feel confident that it is safe with minimal chances of causing failures.

**Comment by benceszasz** [comment]
@Navid200 actually my role was not clear for me, you just wanted to see my opinion or add a review, but I guess then it would be a reviewer.

**Comment by jamorham** [comment]
@benceszasz Assume I know nothing about this functionality. My understanding is you know a lot about this. Please can you confirm whether this PR will work correctly and whether it should be merged? Many thanks.

**Comment by benceszasz** [comment]
@jamorham I confirm that this PR works correctly and can be merged.
As I wrote earlier, this code is also part of my own CareLink xdrip version, but I haven't added this to my PR, because Matthias asked me not to add more changes until my PR gets approved.

**Comment by Navid200** [comment]
>  As I wrote earlier, this code is also part of my own CareLink xdrip version, but I haven't added this to my PR.

This is Navid.
You have an open PR?  If yes, would you please add a link here?

If you don't have an open PR, would you please explain what you mean?

**Comment by jamorham** [comment]
@benceszasz thanks for the clarification.

**Review by jamorham — APPROVED** [review]

**Comment by benceszasz** [comment]
@Navid200 No, currently I don't have an open PR. But the approval of the CareLink Follower datasource PR took more than 1.5 years. The PR was based on my modified xdrip version for following CareLink. During this 1.5 years I have implemented additional features, corrections in my private version and after some time I have added them also to the CareLink Follower PR. At some point Matthias asked me to stop adding changes to the PR, wait for the approval and only add new features in a different PR after the approval of my original PR. This PR containes one of the features, which I have implemented in my private xdrip version, but it was not added to the original CareLink Follower PR, due to Matthias's request. So I know this code well and I know, that it is working :)

**Comment by jamorham** [comment]
@benceszasz any future changes, especially if they only fall within the package for the datasource should get approved significantly more easily. thanks for all your help with this

**Pull request merged**
