### PR TITLE
fix bug wear buffer length

### PR DESCRIPTION
**Pull request by bubbledevteam**
fix bug wear buffer length

### CODE REVIEW

**Comment by bubbledevteam** [comment]
fix bug wear buffer length

**Comment by Lynsullivan** [comment]
Having issues with bubble disconnecting from xDrip+. Have downloaded latest xDrip+ which seems have given me version 2019.10.27 which seems older than my previous 2020 version. Are you working on a fix for this disconnect to bubble?

**Comment by parapenT1sta** [comment]
> Having issues with bubble disconnecting from xDrip+. Have downloaded latest xDrip+ which seems have given me version 2019.10.27 which seems older than my previous 2020 version. Are you working on a fix for this disconnect to bubble?

https://github.com/NightscoutFoundation/xDrip/wiki/How-to-get-the-Nightlies-on-Automatic-Update

**Comment by bubbledevteam** [comment]
> Having issues with bubble disconnecting from xDrip+. Have downloaded latest xDrip+ which seems have given me version 2019.10.27 which seems older than my previous 2020 version. Are you working on a fix for this disconnect to bubble?

Hello,it's off this topic.

I need more details about the disconnections log, you can try to update your xdrip+ to the newest version as @parapenT1sta mentioned. Or send an email to :bubble_devteam@outlook.com

**Pull request merged**
