### PR TITLE
Updated french translations

### PR DESCRIPTION
**Pull request by philippebourget**
- [x] Translation tasks:
- [x] Resources
- [x] MongoDB Settings
- [x] API settings
- [x] WiFi settings
- [x] Location settings
- [x] Broadcast settings
- [x] Amazfit Settings

### CODE REVIEW

**Comment by philippebourget** [comment]
**Should be merged ASAP since the previous translations bring confusion (see example below)**

Finished the essential translations and checked if there was other obvious mistakes. Looks about right for now. 

| Intended ENG | Translation FR | Actual ENG Meaning of FR Translation |
|---------------|----------------|-----------------------|
|"No, keep Parakeet as is."|"Ne pas garder Parakeet comme il est"| Do **not** keep Parakeet as it is. |
|"Possible bad calibration slope, please have a glass of water, wash hands, then recalibrate in a few!"|"Possible mauvaise pente d'étalonnage, allez boire un verre, lavez-vous les mains, puis recalibrez dans quelques temps!"|[...] **Have a drink** (phrased as if you're offering me a beer)|
|"Scan [Dexcom] Share Barcode"|"Numériser Partager Barcode"|"Scan [verb to share] [Barcode is not a french word]"|

**and MUCH, MUCH, more.**

**Comment by MasterPlexus** [comment]
@philippebourget , just a comment for the future after that huge work. You can use crowdin for the translation of your language (and if you are fine and naturally speaker for a language, get also the right as a proof-reader).  
Just check on https://crowdin.com/project/xdrip/fr  
If you have questions on that,you can contact me directly on gitter ;)

**Comment by jamorham** [comment]
Hi, thanks for taking the time to do this. Would you consider proofreading the pending submitted translations at crowdin? https://crowdin.com/proofread/xdrip/7/en-fr these would need to be processed before a PR was processed and there could be conflicts with the translations you've submitted.

**Comment by philippebourget** [comment]
@MasterPlexus Thanks for the heads up. @jamorham had told me about Crowdin, but I had already started on here so I didn't think much of it. I'll go ahead and do that. 

@jamorham I have sent a request to the link above. Thank you!

**Comment by cybernissart** [comment]
I mange to post hundreds of French translation to crowedin repository few month ago but none where validated yet and injected to code.
I don't know what is the trigger to validate them so that they may be included at least in nightly build. 

Do we need to have at least a second review? In which case Philippe your help would be great.
Or should it be validated by a translator moderator?

I surrendered for the moment xDrip translation due to this blocked situation.

**Comment by cybernissart** [comment]
Thanks @philippebourget.
I can see that you manage to validate some entries perhaps in March, as you joined project. 
If you have proofreader right, it would be great indeed to review all validated translations to further go. 
I managed 90% of all strings in December (just dismissed all related to G5, as not being interested initially), but since then code evolved with lot of new ones.

I'll jump into it again, hoping someone will manage them.

**Comment by tolot27** [comment]
@philippebourget @cybernissart You are both proofreaders at crowdin, now. It would be great if you could approve your translations each other and close this PR afterwards.

**Review by cybernissart — APPROVED** [review]

**Comment by tolot27** [comment]
@cybernissart I meant approving the translations at crowdin, not here. We cannot incorporate this PR because we are using the crowdin translation workflow.

**Comment by cybernissart** [comment]
> @cybernissart I meant approving the translations at crowdin, not here. We cannot incorporate this PR because we are using the crowdin translation workflow.

I understood. Changes are effectively done on Crowdin project.
Problem being that we are only two working on the Crowdin french translation, so there is little chance to have them approved in this case, due to this blocking  process.
Translation are pending review for years.

I keep on believing we may achieve it one day and have all work done integrated in the app, to be able to evaluate initial integration, and further tune them. But it now depends on the community... Too reduced to be functional in my own opinion.

**Comment by cybernissart** [comment]
I managed to self review and approved, Philippe and my pending translations.
French string is 100% approved and ok to be merged.

Can you proceed with merging this pull request from Crowdin ?

It will be a big step for french translation !

Regards.

**Comment by tolot27** [comment]
> I managed to self review and approved, Philippe and my pending translations.

Self approving your own translation is sometimes dangerous because you can overlook your own mistakes, easily. But this will be explored by someone else. 

> French string is 100% approved and ok to be merged.

That is really great! Thanks again!

> Can you proceed with merging this pull request from Crowdin ?

There are still some syntactical errors in the translated strings like spaces in URLs or variables which got translated (e.g. in [pref_default_mongodb_uri](https://crowdin.com/proofread/xdrip/all/en-fr?filter=basic&value=0#q=pref_default_mongodb_uri)). After fixing this and checking other languages, I'll inform @jamorham that the new translations are ready to incorporate. He will then create a new release.

**Comment by cybernissart** [comment]
This must be considered as the initial core translation for french strings, that are pending their initial release in app for years.
So for sure it will require review and improvment by me and other contributifs.
We'll then adjust based on real in-app context and errors then.

I'll let you review the few codes change (already done seems like), and hope it will be soon in a nightly release thanks to @jamorham.

Thanks for your time.
Request #825 may be closed, as addressed this morning for the three entries referred.

**Review by tolot27 — APPROVED** [review]
All patched strings are compared to the crowdin translation and adjusted/approved, if necessary.

**Comment by tolot27** [comment]
The next release build will include these changes.

**Pull request closed without merging**
