### PR TITLE
fix #1139: libre status crash when sensor stopped

### LINKED ISSUE #1139: libre status crash when sensor stopped
* use Libre
* stop sensor
* open Status page
* the application will crash

### PR DESCRIPTION
**Pull request by k2s**
Fixes #1139

### CODE REVIEW

**Comment by master3395** [comment]
Not sure if this works, as i haven't tested this change.
But i found it strange, that when the libre stopped, the xdrip+ app crashed, not sure if this is relevant here. (when clicking status)

**Comment by k2s** [comment]
@jamorham This patch is needed otherwise xDrip is crashing.

I am managing 2 real life devices. One with nightly where it crashes and my own xDrip mix containing this patch and that is not crashing.

**Comment by jamorham** [comment]
@k2s thanks for finding this issue. I think a better fix to avoid confusion between xDrip sensor sessions and an actual physical sensor and to display the remainder of mega status when a session has just been stopped, the fix would be better like this to simply exclude the line when the sensor session within xDrip is in stopped state:

```
        final Sensor sensor = Sensor.currentSensor();
        if (sensor != null) {
            l.add(new StatusItem("Libre2 Sensor", sensor.uuid + "\nStart: " + DateFormat.format("dd.MM.yyyy kk:mm", sensor.started_at)));
        }

**Comment by jamorham** [comment]
The way of doing it I mentioned above is included in the Feb 7th Nightly.

**Comment by tolot27** [comment]
Fixed with commit c0b1e91 and merged into nightly [2020.02.07](/NightscoutFoundation/xDrip/releases/tag/2020.02.07).

**Pull request closed without merging**
