### PR TITLE
Tzachi libre2 support

### PR DESCRIPTION
**Pull request by tzachi-dar**
Add support for working with libre2 (still no BT support).

Still under testing.

### CODE REVIEW

**Comment by jamorham** [comment]
How close do you estimate this would be ready to merge? When should I make a review?

**Comment by tzachi-dar** [comment]
I hope it should be ready on this weekend.
Only issue right now is reading multiblocks from the libre2.
I think that we should just remove the "directed" method that does not work on libre2 and we should be fine, but I want to try this first.

**Comment by parapenT1sta** [comment]
> I hope it should be ready on this weekend.
> Only issue right now is reading multiblocks from the libre2.
> I think that we should just remove the "directed" method that does not work on libre2 and we should be fine, but I want to try this first.

Any news? :-)

**Comment by tzachi-dar** [comment]
I'm continuing with BT connection to the device (probably more important).
I hope to have the first version ready at the end of next week.

**Comment by parapenT1sta** [comment]
> I'm continuing with BT connection to the device (probably more important).
> I hope to have the first version ready at the end of next week.

That is fantastic!! 👍

**Comment by tolot27** [comment]
@tzachi-dar Is it ready for testing?

**Comment by tzachi-dar** [comment]
One more day probably.

בתאריך יום א׳, 1 בנוב׳ 2020, 00:53, מאת Mathias Walter ‏<
notifications@github.com>:

**Comment by tzachi-dar** [comment]
Any one who wants to help testing, please see my message at: https://gitter.im/LibreOOPAlgorithm/Lobby

**Comment by tzachi-dar** [comment]
Replaced by https://github.com/NightscoutFoundation/xDrip/pull/1524

**Pull request closed without merging**
