### PR TITLE
Updated test-config

### PR DESCRIPTION
**Pull request by ahaarrestad**
* Updated javadoc in RobolectricTestWithConfig
* Copied app test-config to wear

### CODE REVIEW

**Comment by ahaarrestad** [comment]
@jamorham updated test config as promised.

**Comment by ahaarrestad** [comment]
@jamorham When you have time, this should be quite easy to merge. Test-config is updated as we discussed a couple of weeks ago.

**Comment by jamorham** [comment]
This looks very familiar. Is this a mirror of the test config changes for the wear module?

**Comment by ahaarrestad** [comment]
@jamorham yes it is

**Pull request merged**
