### PR TITLE
Tzachi tomato

### PR DESCRIPTION
**Pull request by tzachi-dar**
First version that reads the tomato.
Still passed very little testing with tomato.

Verified scanning by the phone to make sure that there is no regression.

I'm not able to collect all data that is sent, so I stop on 344, but this gives a bad feeling that I'm not getting all data correctly.

I have disabled printing recieved messages for now, since this allows to get more data.

All comments are welcomed.

### CODE REVIEW

**Comment by gregorybel** [comment]
interesting work! is code based on SDK or is it"reversed engineering"?

**Comment by tzachi-dar** [comment]
Running in the night, a lot of times complete data was not read.

I have changed the functions:
isTomato and isblueReader to not look at DB, and now things seems much better.
Will let it run through the day, and see how it will work.

**Comment by jamorham** [comment]
Reading through it it looks sensible and I assume you have tested the other affected functions like normal NFC reading and the method extraction you have used there is working correctly?

What is the issue regarding the database? Shouldn't it be reading from the cache most of the time?

**Comment by tzachi-dar** [comment]
Here is a short update regarding issue:

It seems that there are two ways for the connection to start: First xDrip starts connection. On this case data will be read correctly.
After 5 minutes, tommato will send the data. It will not be read correctly. Some data will be missing. 

I'll try a nexus5X to understand if a stronger machine is the issue, although since it depends very much on who started the connection, this will look strange. 
Maybe if xDrip is not starting the connection the phone is asleep? would seem strange though since it is not the first packets that gets lost.

I'm not sure why xDrip starts the connection, when it does start it.

Here is a log of a good communication:
============================
03-09 00:13:38.882 32168   550 D jamorham watchupdater: sendWearTreatmentsDataDelete treatments count = 0
03-09 00:13:38.885 32168   550 D UploaderTask: Nothing to upload for: Nightscout REST
03-09 00:13:38.885 32168   550 D jamorham exec: Queue empty: synctoCloudDatabases
03-09 00:13:39.195 13193 13261 W bt_smp  : smp_br_connect_callback is called on unexpected transport 2
03-09 00:13:39.195 13193 13261 W bt_btif : bta_dm_acl_change info: 0x0
03-09 00:13:39.195 13193 13226 D bt_btif_dm: remote version info [db:23:f4:f2:86:62]: 0, 0, 0
03-09 00:13:39.196 13193 13226 E BluetoothRemoteDevices: state12newState0
03-09 00:13:39.197 13193 13226 D BtGatt.GattService: onConnected() - clientIf=5, connId=5, address=DB:23:F4:F2:86:62
03-09 00:13:39.198 32168 32271 D BluetoothGatt: onClientConnectionState() - status=0 clientIf=5 device=DB:23:F4:F2:86:62
03-09 00:13:39.201 32168 32271 D DexCollectionService: Requesting to discover services: previous: NULL
03-09 00:13:39.223 32168 32271 I DexCollectionService: onConnectionStateChange: Connected to GATT server.
03-09 00:13:39.224 32168 32271 D BluetoothManager: getConnectedDevices
03-09 00:13:39.226 13193 13271 D BtGatt.GattService: getDeviceType() - device=30:A8:DB:F2:19:9A, type=3
03-09 00:13:39.226 13193 13271 D BtGatt.GattService: getDeviceType() - device=C6:7E:8B:7E:0D:F0, type=2
03-09 00:13:39.226 32168 32271 I DexCollectionService: checkConnection: Connection state: CONNECTED
03-09 00:13:39.226 32168 32271 I DexCollectionService: checkConnection: Looks like we are already connected, ready to receive
03-09 00:13:39.226 32168 32271 D DexCollectionService: Calling discoverServices
03-09 00:13:39.226 32168 32271 D BluetoothGatt: discoverServices() - device: DB:23:F4:F2:86:62
03-09 00:13:39.227 13193 21294 D BtGatt.GattService: discoverServices() - address=DB:23:F4:F2:86:62, connId=5
03-09 00:13:39.228 13193 13226 D BtGatt.GattService: onSearchCompleted() - connId=5, status=0
03-09 00:13:39.234 32168 32271 D BluetoothGatt: onSearchComplete() = Device=DB:23:F4:F2:86:62 Status=0
03-09 00:13:39.234 32168 32271 D DexCollectionService: Services discovered start
03-09 00:13:39.235 32168 32271 D DexCollectionService: onServicesDiscovered received status: 0
03-09 00:13:39.236 32168 32271 D BluetoothGatt: setCharacteristicNotification() - uuid: 6e400003-b5a3-f393-e0a9-e50e24dcca9e enable: true
03-09 00:13:39.236 13193 13218 D BtGatt.GattService: registerForNotification() - address=DB:23:F4:F2:86:62 enable: true
03-09 00:13:39.236 32168 32271 I DexCollectionService: Bluetooth Notification Descriptor found: 00002902-0000-1000-8000-00805f9b34fb
03-09 00:13:39.236 13193 13226 D BtGatt.GattService: onRegisterForNotifications() - address=null, status=0, registered=1, charUuid=6e400003-b5a3-f393-e0a9-e50e24dcca9e
03-09 00:13:39.241 32168 32271 D DexCollectionService: tomato initialized and data requested
03-09 00:13:39.241 32168 32271 I DexCollectionService: initialize!
03-09 00:13:39.243 32168 32271 I DexCollectionService: sendBtMessage: entered
03-09 00:13:39.243 32168 32271 I DexCollectionService: sendBtMessage: sending message: 
03-09 00:13:39.243 32168 32271 I DexCollectionService: 0x00000000 DD 01                                                       .
03-09 00:13:39.243 32168 32271 D DexCollectionService: Error writing characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e DD01
03-09 00:13:39.243 32168 32271 I DexCollectionService: sendBtMessage: entered
03-09 00:13:39.243 32168 32271 I DexCollectionService: sendBtMessage: sending message: 
03-09 00:13:39.243 32168 32271 I DexCollectionService: 0x00000000 F0                                                          .
03-09 00:13:39.245 32168 32271 D DexCollectionService: Error writing characteristic: 6e400002-b5a3-f393-e0a9-e50e24dcca9e F0
03-09 00:13:39.245 32168 32271 D DexCollectionService: Services discovered end
03-09 00:13:39.245 32168 32271 D DexCollectionService: Services discovered release
03-09 00:13:39.334 32168 32359 D DexCollectionService: onDescriptorWrite: Wrote GATT Descriptor successfully.
03-09 00:13:39.473 17256 17256 W SearchService: Abort, client detached.
03-09 00:13:39.747 32168 32168 D DexCollectionService: Succeeded writing characteristic: (2nd try) 6e400002-b5a3-f393-e0a9-e50e24dcca9e DD01
03-09 00:13:39.747 32168 32168 E DexCollectionService: Error writing characteristic: (2nd try) 6e400002-b5a3-f393-e0a9-e50e24dcca9e F0
03-09 00:13:39.750 32168 32358 D DexCollectionService: OnCharacteristic WRITE:  status: Gatt Success data: F0 uuid: 6e400002-b5a3-f393-e0a9-e50e24dcca9e
03-09 00:13:40.576 13193 13261 I bt_bta_dm: bta_dm_gatt_disc_result service_id_uuid_len=2 
03-09 00:13:40.576 13193 13261 I bt_bta_dm: bta_dm_gatt_disc_result service_id_uuid_len=2 
03-09 00:13:40.576 13193 13261 I bt_bta_dm: bta_dm_gatt_disc_result service_id_uuid_len=16 
03-09 00:13:40.576 13193 13261 I bt_bta_dm: bta_dm_gatt_disc_result service_id_uuid_len=16 
03-09 00:13:42.365 32168 32182 E DexCollectionService: Recieved a buffer after 58 seconds, starting again. already connected 1420bytes.


Here is a log of a bad communication:
============================
03-09 00:12:41.759 32168 32359 E DexCollectionService: Recieved a buffer after 298 seconds, starting again. already connected 1971bytes.
03-09 00:12:41.850 32168 32359 E DexCollectionService: Starting to acumulate data expectedSize = 1971
03-09 00:12:42.239 32168 32182 E DexCollectionService: We have the data that we want
03-09 00:12:42.252 32168 32182 E DexCollectionService: We have all the data that we need

**Comment by jamorham** [comment]
Ok let me know if this is ready for merging. thanks

**Pull request merged**
