### PR TITLE
Add Support for MiaoMiao / Libre2 using OOP2 on wear app.

### PR DESCRIPTION
**Pull request by tzachi-dar**
This PR is based on the great work done by [cr-ellis](https://github.com/cr-ellis)
[Colin Ellis](https://github.com/cr-ellis) https://github.com/NightscoutFoundation/xDrip/pull/2498

I have also added here the changed needed in order to have all error checks and other fixes that have been done for libre2 app on the last 2 years.

This checkin looks huge, but it is not.
There are small changes to the tomato.java code, used to allow using a dead sensor with the code.

app/src/main/java/com/eveningoutpost/dexdrip/Models/FakeLibreData.java	
app/src/main/java/com/eveningoutpost/dexdrip/Models/Tomato.java	

The following files have changes, but changes are rather small and quite straght forward:
wear/src/main/AndroidManifest.xml	
wear/src/main/java/com/eveningoutpost/dexdrip/GcmActivity.java	
wear/src/main/java/com/eveningoutpost/dexdrip/Home.java	
wear/src/main/java/com/eveningoutpost/dexdrip/Models/ActiveBluetoothDevice.java
wear/src/main/java/com/eveningoutpost/dexdrip/Models/BgReading.java
wear/src/main/java/com/eveningoutpost/dexdrip/Models/JoH.java
wear/src/main/res/values/strings.xml	

The following files have just been copied from the app version and should have no diffeance from the app version.
This can be verified by the command:

comp app\src\main\java\com\eveningoutpost\dexdrip\LibreAlarmReceiver.java wear\src\main\java\com\eveningoutpost\dexdrip\LibreAlarmReceiver.java
comp app\src\main\java\com\eveningoutpost\dexdrip\Models\FakeLibreData.java wear\src\main\java\com\eveningoutpost\dexdrip\Models\FakeLibreData.java
comp app\src\main\java\com\eveningoutpost\dexdrip\Models\GlucoseData.java wear\src\main\java\com\eveningoutpost\dexdrip\Models\GlucoseData.java
comp app\src\main\java\com\eveningoutpost\dexdrip\Models\LibreOOPAlgorithm.java wear\src\main\java\com\eveningoutpost\dexdrip\Models\LibreOOPAlgorithm.java
comp app\src\main\java\com\eveningoutpost\dexdrip\Models\ReadingData.java wear\src\main\java\com\eveningoutpost\dexdrip\Models\ReadingData.java
comp app\src\main\java\com\eveningoutpost\dexdrip\UtilityModels\BridgeResponse.java wear\src\main\java\com\eveningoutpost\dexdrip\UtilityModels\BridgeResponse.java
comp app\src\main\java\com\eveningoutpost\dexdrip\UtilityModels\Constants.java wear\src\main\java\com\eveningoutpost\dexdrip\UtilityModels\Constants.java
comp app\src\main\java\com\eveningoutpost\dexdrip\UtilityModels\Intents.java wear\src\main\java\com\eveningoutpost\dexdrip\UtilityModels\Intents.java
comp app\src\main\java\com\eveningoutpost\dexdrip\UtilityModels\LibreUtils.java wear\src\main\java\com\eveningoutpost\dexdrip\UtilityModels\LibreUtils.java
comp app\src\main\java\com\eveningoutpost\dexdrip\UtilityModels\PersistentStore.java wear\src\main\java\com\eveningoutpost\dexdrip\UtilityModels\PersistentStore.java
comp app\src\main\java\com\eveningoutpost\dexdrip\utils\LibreTrendPoint.java wear\src\main\java\com\eveningoutpost\dexdrip\utils\LibreTrendPoint.java
comp app\src\main\java\com\eveningoutpost\dexdrip\utils\LibreTrendUtil.java wear\src\main\java\com\eveningoutpost\dexdrip\utils\LibreTrendUtil.java

The files below are coppied from the app with very small changes.
I use the following command to compare them:

winmergeu app/src/main/java/com/eveningoutpost/dexdrip/Models/LibreBlock.java	wear/src/main/java/com/eveningoutpost/dexdrip/Models/LibreBlock.java	
winmergeu app/src/main/java/com/eveningoutpost/dexdrip/Models/SensorSanity.java wear/src/main/java/com/eveningoutpost/dexdrip/Models/SensorSanity.java
winmergeu app/src/main/java/com/eveningoutpost/dexdrip/Models/Tomato.java wear/src/main/java/com/eveningoutpost/dexdrip/Models/Tomato.java
winmergeu app/src/main/java/com/eveningoutpost/dexdrip/NFCReaderX.java wear/src/main/java/com/eveningoutpost/dexdrip/NFCReaderX.java
winmergeu app/src/main/java/com/eveningoutpost/dexdrip/NSEmulatorReceiver.java wear/src/main/java/com/eveningoutpost/dexdrip/NSEmulatorReceiver.java
winmergeu app/src/main/java/com/eveningoutpost/dexdrip/utils/DexCollectionType.java wear/src/main/java/com/eveningoutpost/dexdrip/utils/DexCollectionType.java

### CODE REVIEW

**Comment by cr-ellis** [comment]
Looks good to me.

**Comment by Unai-HP** [comment]
> If anyone wants to test, it can be done using this wear apk:https://drive.google.com/file/d/1PdU3-qT3Bhp9UpOi_kuVVFmNZdmuDYhK/view?usp=sharing One will also have to install OOP2 from here: https://drive.google.com/file/d/1vu3x4rvggb2k2rVlTc0kb1t4Yk_ULin5/view?usp=sharing On some phones, one will also have to set "use direct intent" on the oop2 UI.

I've tried it but the watch doesn't collect values. My specs: Android 13 with a Samsung Watch (Wear 3.5). I installed oop2 through adb as an apk and wear_apk with wear installer (i think it uses adb too, but just in case it helps). xDrip wear connects to the phone but when I enable "force collector" I don't get values. OOP2 doesn't show anything under "values", in the UI.

**Comment by tzachi-dar** [comment]
> 

@Unai-HP Just making sure, you are using it with miaomiao device right?
If this is the case, can you use ADB to capture the logs on the watch for 15 minutes after you switch to wear and post here the logs (or send them to me at tzachi.dar@gmail.com).

**Comment by Unai-HP** [comment]
> > 
> 
> @Unai-HP Just making sure, you are using it with miaomiao device right? If this is the case, can you use ADB to capture the logs on the watch for 15 minutes after you switch to wear and post here the logs (or send them to me at [tzachi.dar@gmail.com](mailto:tzachi.dar@gmail.com)).

Oh, ok, no I'm not using a miaomiao device. Since the title has that slash I thought that It could be used with Libre2+oop2 alone. If its not possible I'm sorry, I missundertood the title. However I think it would be a great feature, and not very hard to implement (I think). I'll try so when this is merged, if there is no one doing that already.

**Comment by SimonPhilpott** [comment]
So I managed to install OOP2 fine using ADB, but trying to install the WearOS through Wear installer failed, and thorugh ADB I got this error message. 

Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.eveningoutpost.dexdrip signatures do not match previously installed version; ignoring!]

I'll try an uninstall of the previous version and see if that bypasses the signatures issue.

**Comment by SimonPhilpott** [comment]
So that allowed me to install, documenting this for the benefit of others. 

- I've got no initial results showing on the watch from the phone, to be expected. Rebooted and collected two more values on my phone to see if it was sent to my watch. So there seems to be a lack of communication to the phone from my wtach. 
- Switching off my phone as the collector through Xdrip setting, but retaining the Watch Initgration + Wear collection service + Force Wear. 
- Then switching on the Watch as the collector also - physically on the watch since I can't send setting changes from my phone, while running OOP2 on the watch too. Xdrip preferences, Enable collector, Force collector. Currently there is no bluetooth device found on the Xdrip system status screen

**Comment by SimonPhilpott** [comment]
- Attempted to connect to the miaomiao through my watch, via settings > connections > bluetooth > devices. No change.
- Rebooted both devices, no change in status on the Phone. i.e. Watch sevice forced, Bluetooth device disconnected. On my phone, the device running the collection service (found under Android Wear Integration) is blank.
- No results collected after 30 mins. All foreground settings  in OOP2 on the watch are set to on, I've tried with 10 min itervals switching various settings on OOP2 on/off and giving it chance to collect values. 

It looks like the communication between Xdrip on my phone (v 2023.02.15) isn't communicating with my watch Xdrip app (libre2-wear-2023.01.31).

**Comment by tzachi-dar** [comment]
In order for connection between your watch and phone to work you need to have them both built and signed using the same key.
So, either you build both the wear apk and the xdrip apk on your machine and install them, or you should use the apk that I supplied above. In that case, you will need to use xDrip from https://drive.google.com/file/d/1fuayz7zNdT-4qdCC2VXB1YlhIDqL9jLR/view?usp=sharing

**Comment by SimonPhilpott** [comment]
> In order for connection between your watch and phone to work you need to have them both built and signed using the same key. So, either you build both the wear apk and the xdrip apk on your machine and install them, or you should use the apk that I supplied above. In that case, you will need to use xDrip from https://drive.google.com/file/d/1fuayz7zNdT-4qdCC2VXB1YlhIDqL9jLR/view?usp=sharing

I'll remove all version from both devices and try again later today, I'll capture wear logs trough ADB too so I've got something to share on top of my activity.

**Comment by SimonPhilpott** [comment]
There seems to be a few minutes delay picking up the data value from the watch, so the 5min reading tends to hit the phone at 7-8mins. Probably down to OOP2 working the incoming data before passing it. Not sure if there is anything that can be done with that but worth mentioning. The processor on the TicWatch Pro 3 ultra isn't too bad but not as efficient as a phones might be. Also probably part of this.

**Comment by cr-ellis** [comment]
What's the timescale for getting this merged into a pre-release?

**Comment by jamorham** [comment]
@tzachi-dar do you think this is ready for merge?

**Comment by tzachi-dar** [comment]
Yes, this can be merged.

**Review by jamorham — APPROVED** [review]

**Comment by Pawlacz23** [comment]
Hi, is three any chance to avoid using Miao Miao (any addiotional bridge) and connect directly smartwatch wear os with libre 2 (fsl2) using oop2 as collector?

Additionally, I'd like to treat smartwatch as standalone collector and use it for sending figuers to master phone and redirect data to followers...
Do you have any idea, please?

I know three is a chance to connect it directly via juggluco but in my opinion oop2 & xdrip is a better solution for my glucose.

**Comment by jamorham** [comment]
@tzachi-dar There are actually problems with this PR. The packages are incorrect at least in `LibreBlock.java` I will see if I can resolve.

**Comment by tzachi-dar** [comment]
Is the issue solved? Do you need help from me?

**Comment by SimonPhilpott** [comment]
Did this hit nighties?

**Comment by Navid200** [comment]
> Did this hit nighties?

@SimonPhilpott You can see "Merged" at the top, no?

And these are the release notes:  https://navid200.github.io/xDrip/docs/ReleaseNotes.html

**Comment by SimonPhilpott** [comment]
@Navid200 apologies, I had noticed it had changed.

**Comment by rvilchez1** [comment]
> Hi, is three any chance to avoid using Miao Miao (any addiotional bridge) and connect directly smartwatch wear os with libre 2 (fsl2) using oop2 as collector?
> 
> Additionally, I'd like to treat smartwatch as standalone collector and use it for sending figuers to master phone and redirect data to followers... Do you have any idea, please?
> 
> I know three is a chance to connect it directly via juggluco but in my opinion oop2 & xdrip is a better solution for my glucose.


Any chance that this request is being developed in the near term?
connecting directly to the Libre2 without Miao would be a great feature

**Pull request merged**
