### PR TITLE
Tzachi libre average

### PR DESCRIPTION
**Pull request by tzachi-dar**
This PR is needed in order to have more stable results, and more immunity to libre sensor noise.

The main idea is to use an average of 5 points instead of one point.
This promises that noise will be smaller and programs like openaps will get more stable results.

Still needs more testing.

### CODE REVIEW

**Comment by tzachi-dar** [comment]
Here is an example from two xdrips, running on the same data, one with the new algorithm and one without it:

Without it:



screenshot_20181218-230729_xdrip 1

**Comment by tzachi-dar** [comment]
Here are the pictures after the change:
screenshot_20181218-230842_xdrip 1
screenshot_20181218-231027_xdrip 1

**Comment by tzachi-dar** [comment]
And here is a graph of both showing the smaller noise:
image

**Comment by bcllivewire** [comment]
Where did you down load XDrip from , I have tried looking on Nightscout site but cannot find , I long in but no results ,
Can somebody help with this 
Brian

**Comment by tzachi-dar** [comment]
@bcllivewire Is your question related to this pr?
If not, the latest stable version of xdrip can be downloaded from: https://bit.do/xdrip-plus

**Comment by bcllivewire** [comment]
Thanks
I am up and running now with Xdrip 
Brian

**Comment by tzachi-dar** [comment]
I have rebased this over master in https://github.com/NightscoutFoundation/xDrip/pull/828

**Pull request closed without merging**
