### PR TITLE
Add poll delay for Nightscout Follow

### LINKED ISSUE #929: nightscout follower delayed by 5 to 10 min.
using xdrip to follow my kids bg. prefer xdrip as follower app because of the prediction display. but the bg data gets delayed by 5 to 10 min. have to restart collector everytime. and gettin error like 'nightscout follower.  woke up early'. is there a way to get xdrip to ping nightscout site si it gets latest bg value always?

### PR DESCRIPTION
**Pull request by ahaarrestad**
Enabling a poll delay for Nightscout follow to reduce the time from
a new value is made available on Nightscout until xdrip polls for new
data. Depending on the setup of nightscout this might be anything
between 0 and 150 seconds. Minimum value is set to 0s. Max is 300s.

This pull request fixes #929 by allowing custom poll delay.

@jamorham tested in AVD and works fine. There are sanity checks for input values.

### CODE REVIEW

**Comment by ahaarrestad** [comment]
Don't merge yet. Found a bug when changing collector. The new property is not removed / only shown for nsfollow.

**Comment by ahaarrestad** [comment]
Found bug and corrected it. Poll delay now only shows for Nightscout Follow

**Comment by jamorham** [comment]
Can you explain in more detail what this is for?

**Comment by ahaarrestad** [comment]
I can add more explanation in code / docs too.

The goal is to let the user try to tune xdrip into fetching data after the last data has arrived in nightscout. For dexcom bridge the default poll interval on nightscout is 2.5 minutes, but not linked directly to when the last data was received. This interval can be changed in nightscout, but still it is very hard to automatically find the right interval for each persons individual setup. The simplest way is to let the user choose a poll-delay, which makes use of less cpu and bandwidth (ask once), and at the same time receive the update as soon as possible after the data was made available in nightscout.

**Comment by ahaarrestad** [comment]
As the issue too states: "Experienced delay is about 5 minutes". This might be OK for some and others will want to reduce the time though the bridge and poll.

**Comment by ahaarrestad** [comment]
@jamorham I will try to get a fix to Nightscout, but until then it is your call if you want this added to xdrip or if we should abandon the pr :-)

**Comment by FredMK** [comment]
This PR would be a big help for Nightscout users, please accept it. The fixed 10 seconds poll delay is not enough.

**Comment by seletok** [comment]
Hello,
I have Latest BG in XDrip+ (Follower from Nightscout) up to 9 mins. Is it possible to make it shorter? Max 5 minute, that is the BG measure period?

Thank you.
Regards,

**Comment by ahaarrestad** [comment]
How much delay is there in nightscout for bg data? You can reduce that time and xdrip will pick it up. Check the poll interval for dexcom follow in nightscout docs and add it to your config for nightscout.

**Comment by ahaarrestad** [comment]
Config variables can be found here https://github.com/nightscout/cgm-remote-monitor#bridge-share2nightscout-bridge

**Comment by seletok** [comment]
I have Medtronic 640g with CNL 2,4. CNL 2.4 connected to a Xperia x Compact to upload data to Nightscout. In Nightscout data refresh in a few second.
From Nightscout download to Xdrid+ installed on a S10.

**Comment by ahaarrestad** [comment]
Contact me on gitter and I can try to have a look at it.

**Comment by seletok** [comment]
Sorry... I am a newbie... How can I do this?

**Comment by seletok** [comment]
I write to you. Do you see?

> 
> 
> Contact me on gitter and I can try to have a look at it.

I write to you. Do you see?

**Pull request closed without merging**
