### PR TITLE
Tzachi libre uploader2

### PR DESCRIPTION
**Pull request by tzachi-dar**
This code allows xdrip to also upload the libre data that it reads to a mongodb.

This data then allows another xdrip to show results. 
Can be used for all house coverage or two parents running xdrip with two phones transparently.

### CODE REVIEW

**Comment by tzachi-dar** [comment]
This was checked a few more days and works well.

**Comment by jamorham** [comment]
Hi, can you explain why the uploads are enabled for `Tomato` but not `Blucon` or `LibreAlarm` ? What is the reason for this? thanks

**Comment by tzachi-dar** [comment]
For librealarm, the main reason is testing. it should probably work. I can test it, if you think that someone is still using it.
For blukon, there are two modes:
1) where raw data is used. In this case, we simply just don't have all the data, so the reading part will now know how to parse it.
2) When oop is used, we have all the data, but we need to test it. If you think it is important, we can ask someone to test it.

**Comment by jamorham** [comment]
Okay. If you create another signature for ` HandleGoodReading` which handles the arguments as they were and then calls your updated method with the default as `false` then you can eliminate a lot of the changes to unrelated classes. The same is probably true for `LibreBlock.createAndSave`. 

What I would like to see is the minimum amount of changes to unrelated code paths. Overall I am not a fan of expanding the methods to pass parameters down multiple levels, but due to the organic way the code has grown and its structure, this may be unavoidable. But I think it can be neatened up by preserving the previous signatures with compatibility methods as I mentioned above.

**Comment by tzachi-dar** [comment]
Created the two old functions.
I'm doing final testing for the new version.

**Comment by tzachi-dar** [comment]
Verified with the new code. works well.

**Comment by tzachi-dar** [comment]
Thanks.

**Pull request merged**
