### PR TITLE
Change Stop Sensor page

### PR DESCRIPTION
**Pull request by Navid200**
There are cases where a user accidentally stops their sensor.
#1309
This comes up occasionally on facebook as well.
The user intends to go to the system status page or another page, but, accidentally taps on "Stop Sensor" and end up on the stop sensor page and stop sensor.
I can see how annoying it can be if I made such a mistake.

There are requests for the stop sensor button, on the main menu, to be relocated.
I believe that is an extreme change.

Instead of moving the button, I have edited the stop sensor page to make it stand out so that the user hopefully can realize that they are on a page other than the one they intended.
Currently the stop sensor page looks like this:

I have changed it to look this way:

I have intentionally picked ugly colors, different from the xDrip norm colors.
I have intentionally written a long story and I have added warning at the top.
The intent is to give visual cues to a user who may be half sleep or hypoglycemic or riding a bicycle etc. that they are on the wrong page.

### CODE REVIEW

**Comment by tzachi-dar** [comment]
I think this is too frightening for the normal user.
A sensor can be stopped and started again. This solves some problem.
The wording might need to reflect that this is not that dangerous.

**Comment by Navid200** [comment]
@tzachi-dar Thanks for the feedback.  Understood.

Would it be better if I add the following paragraph after?

However, if you indeed intend to stop sensor or clear calibrations, you are on the right page.

**Comment by Navid200** [comment]
@tzachi-dar Is there a way to stop and start a sensor without losing all the existing calibrations?

**Comment by Navid200** [comment]
I think we can even go back to the original text if you prefer as long as we keep the colors.  Please see this image.




Again, I hope the colors will provide a visual cue to someone who is not reading the text.

Would this be acceptable?

**Comment by tzachi-dar** [comment]
This makes more sense now.
Please note that stopping a sensor is meant to clear all calibrations, in order to have a new start. No reason to keep them.

**Comment by tzachi-dar** [comment]
By the way, this PR only changes two files, any reason why it has 96 commits?
Maybe recreate it with relevant files only?

**Comment by Navid200** [comment]
It's because I am trying to find my way around Github!  I am sorry abut that.
I will close this and open a new pull request.

**Pull request closed without merging**
