### PR TITLE
start documentation of translation process

### PR DESCRIPTION
**Pull request by k2s**
add: script example to keep translation in sync when english (main) strings change

### CODE REVIEW

**Comment by tolot27** [comment]
@k2s It is a good idea to have translation documented. Please can you change this PR to describe the usage of [crowdin](https://crowdin.com/project/xdrip) and add/describe a screenshot of the xDrip app showing the menue with the menue item "Crowd-sourced stranslation".

**Comment by tolot27** [comment]
@k2s It is also important to highlight that variable names should not be translated.

**Comment by Navid200** [comment]
How much longer is this pull request going to be left open?

Am I wrong to assume that a pull request should either be merged or closed?
If the person who has opened the pull request is not responding, what would be the point of leaving it open?  For how long?

**Comment by Navid200** [comment]
Would you please close this pull request?

**Pull request closed without merging**
