### PR TITLE
add Hungarian and Ukrainian language to menu

### PR DESCRIPTION
**Pull request by tolot27**
Add hungarian to the "Chose a specific language" menu and sorts the language entries.
Hungarian is currently in [translation](https://crowdin.com/project/xdrip/hu).

### CODE REVIEW

**Comment by jamorham** [comment]
I see that the the ordering has also changed. How certain are you that the order is still correct with regards to the mapping of language name to locale code? It isn't easy to see from the diff..

**Comment by tolot27** [comment]
> I see that the the ordering has also changed. How certain are you that the order is still correct with regards to the mapping of language name to locale code? It isn't easy to see from the diff..

I've created a two-column table of the two arrays prior ordering to ensure consistency.

**Comment by tolot27** [comment]
Ukrainian translation is approved at Crowdin. We can continue to merge.

**Comment by tolot27** [comment]
> > I see that the the ordering has also changed. How certain are you that the order is still correct with regards to the mapping of language name to locale code? It isn't easy to see from the diff..
> 
> I've created a two-column table of the two arrays prior ordering to ensure consistency.

| **ISO 639-1** | **native name** |
|---------------|-----------------|
| nb            | Bokmal          |
| cs            | čeština         |
| de            | Deutsch         |
| en            | English         |
| es            | Español         |
| fr            | Français        |
| hr            | Hrvatski        |
| it            | Italiano        |
| hu            | magyar          |
| nl            | Nederlands      |
| no            | Norsk           |
| pl            | Polski          |
| pt            | Português       |
| ro            | Română          |
| sk            | Slovenčina      |
| fi            | Suomi           |
| sv            | Svenska         |
| ru            | русский         |
| iw            | עברית           |
| ko            | 한국어          |
| uk            | Українська      |

@jamorham You can validate it again, if you like.

**Review by jamorham — APPROVED** [review]

**Comment by nightscout-ricsi** [comment]
Unfortunately I can not change to Hunagrian language. I can selct it in the menu, I can switch to ON the force button, but the interface does not changes.

**Comment by tolot27** [comment]
@nightscout-ricsi You may have noticed that with commit 7500a05 only 14 translated strings were merged. I've seen at Crowdin that more than 4,300 translations were approved at 16th, April but Crowdin did not create a new commit at https://github.com/jamorham/xDrip-plus/commits/l10n_master7. That is because there was a sync error at 13:19 Apr 15, 2021.
I've resumed the synchronization at the translation should be available with the next nightly release.

**Comment by nightscout-ricsi** [comment]
Thanks, now it works!

**Pull request merged**
