### PR TITLE
Tzachi compare cgms

### PR DESCRIPTION
**Pull request by tzachi-dar**
Not 100% xdrip, but something that I think that many in the community will find interesting:

This is a small utility that can be used to compare CGMS.
It reads data from:
1) Finger pricks (freestyle light).
2) xDrip (better be follower, so calibrations don't disturb the data).
3) Libre (the program shows the difference between actual reading, and interpreted readings).

An example to the output:

Final results
Finger Pricks                  xdrip results                    libre results
27/11/2016 20:13  108    106.6 1.5 (sensor age = 2.9)                      87.0 4.0
27/11/2016 23:37  217    119.2 0.4 (sensor age = 3.0)                     202.0 2.0
28/11/2016 02:52  209    281.3 0.4 (sensor age = 3.2)                    179.0 10.0
28/11/2016 07:18   94    117.4 1.4 (sensor age = 3.3)       45.0 5.0  (interpulated)
28/11/2016 08:48   46        ------------------------       68.0 4.0  (interpulated)
28/11/2016 13:46   82    142.1 4.5 (sensor age = 3.6)                    126.0 12.0
28/11/2016 13:52   74    121.9 0.5 (sensor age = 3.6)                     106.0 6.0
28/11/2016 20:38  251    202.7 1.5 (sensor age = 3.9)                     247.0 6.0
28/11/2016 21:56   76     97.7 4.5 (sensor age = 4.0)                      66.0 1.0
28/11/2016 22:07  116     76.1 0.5 (sensor age = 4.0)                     65.0 10.0
28/11/2016 23:02  127     71.6 0.5 (sensor age = 4.0)      125.0 2.0  (interpulated)
29/11/2016 00:42  196    150.4 0.5 (sensor age = 4.1)                     177.0 1.0
29/11/2016 02:32  106     97.0 0.5 (sensor age = 4.1)                      81.0 5.0
29/11/2016 03:20   91     79.6 3.5 (sensor age = 4.2)       76.0 4.0  (interpulated)
29/11/2016 07:18  140     46.4 1.5 (sensor age = 4.3)                     102.0 1.0
29/11/2016 09:09  256    204.6 2.6 (sensor age = 4.4)      277.0 7.0  (interpulated)
29/11/2016 12:51  232    268.8 9.6 (sensor age = 4.6)                     279.0 1.0
29/11/2016 13:42  131    176.3 0.5 (sensor age = 4.6)                     151.0 1.0
29/11/2016 16:58  242    187.2 1.6 (sensor age = 4.7)                    250.0 10.0
29/11/2016 20:12  116    125.9 0.5 (sensor age = 4.9)                     164.0 1.0
29/11/2016 22:40  189    111.8 3.5 (sensor age = 5.0)                     179.0 1.0
30/11/2016 02:10  223    189.6 3.5 (sensor age = 5.1)                     199.0 2.0
30/11/2016 06:50  183    198.6 3.5 (sensor age = 0.2)                     152.0 2.0
30/11/2016 06:51  254    198.6 4.5 (sensor age = 0.2)                     152.0 3.0
30/11/2016 12:16  197    299.0 4.7 (sensor age = 0.4)     247.0 11.0  (interpulated)
30/11/2016 13:44   55    113.5 2.6 (sensor age = 0.5)       81.0 9.0  (interpulated)
30/11/2016 16:20  120    215.6 3.6 (sensor age = 0.6)                     152.0 1.0
01/12/2016 01:28  174    222.1 1.5 (sensor age = 1.0)                     163.0 1.0
01/12/2016 03:38  113    137.7 1.5 (sensor age = 1.1)                      93.0 6.0
01/12/2016 06:10  144    164.7 3.5 (sensor age = 1.2)      146.0 4.0  (interpulated)
01/12/2016 06:53  135    168.0 1.5 (sensor age = 1.2)                     134.0 1.0
01/12/2016 13:16  210    201.4 4.6 (sensor age = 1.5)      232.0 9.0  (interpulated)
01/12/2016 17:38  208    185.2 1.6 (sensor age = 1.6)      224.0 1.0  (interpulated)
01/12/2016 19:29  179    153.2 2.6 (sensor age = 1.7)      205.0 7.0  (interpulated)
01/12/2016 20:15  111    108.7 3.5 (sensor age = 1.7)      127.0 7.0  (interpulated)
01/12/2016 20:37  108     77.8 0.6 (sensor age = 1.8)                    109.0 12.0
02/12/2016 02:05  155    120.6 3.6 (sensor age = 2.0)                     176.0 2.0
02/12/2016 04:24  231    179.0 2.7 (sensor age = 2.1)                     237.0 1.0
02/12/2016 07:16  132     55.7 4.7 (sensor age = 2.2)                    140.0 11.0
02/12/2016 08:34  150     74.1 2.7 (sensor age = 2.3)     203.0 11.0  (interpulated)
02/12/2016 13:06  155    180.0 4.6 (sensor age = 2.4)                     190.0 3.0
02/12/2016 13:09  139    213.7 2.6 (sensor age = 2.4)                     190.0 6.0
02/12/2016 19:20  233    250.8 3.6 (sensor age = 2.7)     273.0 10.0  (interpulated)
02/12/2016 20:24   72    125.4 2.6 (sensor age = 2.8)       ------------------------
03/12/2016 01:52  108    146.5 0.7 (sensor age = 0.0)                     101.0 2.0
03/12/2016 05:46  322    301.1 4.7 (sensor age = 0.2)      350.0 5.0  (interpulated)
03/12/2016 08:56  105     81.5 4.7 (sensor age = 0.3)       ------------------------
03/12/2016 14:31   68     75.1 4.8 (sensor age = 0.6)       ------------------------
03/12/2016 23:26  173     97.2 4.7 (sensor age = 0.9)                     161.0 1.0
04/12/2016 02:35  180    171.5 3.7 (sensor age = 1.1)                     163.0 6.0
04/12/2016 02:36  175    171.5 4.7 (sensor age = 1.1)                     163.0 7.0
04/12/2016 06:13  148    110.5 1.7 (sensor age = 1.2)                    122.0 11.0
04/12/2016 13:28  223    233.0 1.7 (sensor age = 1.5)                     269.0 6.0
04/12/2016 14:15  100    150.8 3.7 (sensor age = 1.5)                     158.0 8.0
04/12/2016 22:18  235    130.2 1.7 (sensor age = 1.9)      241.0 4.0  (interpulated)
05/12/2016 02:53   92     97.6 1.8 (sensor age = 2.1)       94.0 8.0  (interpulated)
05/12/2016 04:01  142     53.2 4.8 (sensor age = 2.1)      142.0 1.0  (interpulated)
05/12/2016 06:25  195     91.8 3.8 (sensor age = 2.2)                     222.0 2.0
05/12/2016 07:42  226    261.2 0.7 (sensor age = 2.3)     240.0 12.0  (interpulated)
05/12/2016 12:49   94    104.6 2.8 (sensor age = 2.5)                      95.0 1.0
05/12/2016 16:12  147    178.4 0.8 (sensor age = 2.6)     162.0 11.0  (interpulated)
05/12/2016 16:49  127    120.0 2.8 (sensor age = 2.7)      131.0 3.0  (interpulated)
05/12/2016 19:31  320    115.9 4.7 (sensor age = 2.8)                     327.0 7.0
05/12/2016 21:39   62     65.4 2.8 (sensor age = 2.9)       77.0 7.0  (interpulated)
05/12/2016 22:10   58     44.8 3.8 (sensor age = 2.9)       47.0 8.0  (interpulated)
06/12/2016 00:49  140     74.7 2.8 (sensor age = 3.0)                     155.0 1.0
06/12/2016 04:34  190    178.8 2.8 (sensor age = 0.1)                     210.0 1.0
06/12/2016 07:00  176    150.9 3.8 (sensor age = 0.2)                     173.0 1.0
06/12/2016 20:13   77     93.1 1.8 (sensor age = 0.8)                     114.0 2.0
06/12/2016 23:26  139     92.8 4.8 (sensor age = 0.9)                     151.0 1.0
xDrip histogram

total objects = 114.0
  < 10% = 23.68421052631579
  < 20% = 15.789473684210526
  < 30% = 21.92982456140351
  others 38.59649122807018

xLibre histogram

total objects = 67.0
  < 10% = 41.791044776119406
  < 20% = 28.35820895522388
  < 30% = 11.940298507462687
  others 17.91044776119403

Please note that dexcom should probably look better, but IMHO, my transmitter is dying, and sensors don't last more than 2-3 days.

### CODE REVIEW

**Comment by tzachi-dar** [comment]
Also create a calibration graph for each sensor.

**Comment by jamorham** [comment]
I think the readme should be expanded to explain how to construct the source data input formats and how to interpret the output data, otherwise this is going to be difficult for a wider audience to make use of.

**Comment by tzachi-dar** [comment]
Sure, I'm adding one more graph, and then I'll document everything correctly.

**Comment by tzachi-dar** [comment]
Readme file updated.
Please let me know if there are changes needed.

**Comment by jamorham** [comment]
The readme file looks comprehensive now but there appears to be some unrelated changes to GcmListenerSvc.java included. I assume committing of those were unintended.

**Comment by tzachi-dar** [comment]
Yes, GcmListenerSvc.java was unintended, I'll fix that tonight.
Tzachi

**Comment by tzachi-dar** [comment]
Reverted changes in GcmListenerSvc.java.

**Pull request merged**
