### PR TITLE
add Diabox Data Source

### PR DESCRIPTION
**Pull request by bubbledevteam**
add Diabox Data Source

### CODE REVIEW

**Comment by bubbledevteam** [comment]
add Diabox Data Source

**Comment by bubbledevteam** [comment]
Here is the BubbleFirmware recourses

**Comment by jamorham** [comment]
Can you explain the reason for this PR, what does it do? 
Why is a new data source needed here?
Thanks.

**Comment by Artemdrip** [comment]
Diabox curves are very smooth and stable.

screen-1

**Comment by nvanderperren** [comment]
Why is this closed? I like to connect my diabox with xdrip.

**Pull request closed without merging**
