### PR TITLE
Cleanup of code in StatusItem

### PR DESCRIPTION
**Pull request by ahaarrestad**
* Inlined colorHint in enum
* Removed unused code

### CODE REVIEW

**Comment by ahaarrestad** [comment]
@jamorham Some minor code cleanup. Found this code when writing the MegaStatus for Nightscout Follow

**Comment by jamorham** [comment]
Thanks. I don't remember the history exactly but do you think `colorHint` is excessively complex because it can't ever actually receive a value not present in the enum?

**Comment by ahaarrestad** [comment]
I believe it was written by someone who didn't know that you can add properties to enums in java. I have seen that before. All calls are to the same methods now as they were.

**Review by jamorham — APPROVED** [review]
Looks good

**Pull request merged**
