### PR TITLE
Tidepool Upload Duplication #865

### PR DESCRIPTION
**Pull request by psonnera**
https://github.com/NightscoutFoundation/xDrip/issues/865
Quick fix. Please review and let me know if there is an impact on the Tidepool system I haven't thought of.

### CODE REVIEW

**Comment by jamorham** [comment]
Can you explain why this is targeting low level methods relating to validity of boluses etc instead of wrapping the preference option around lines like `records.addAll(getTreatments(start, end));` in `UploadChunk` ? 

This also adds a dependency on `Pref` to the lower level classes which causes the unit tests to fail.

**Comment by psonnera** [comment]
@jamorham you're right. And it's not even working since I forgot it's also pushed by EWizard. This is probably because I had no clue where to start in the code. Using your question I will try to find something more consistent. Sorry. Learning. And need that feature. Please discard.

**Comment by jamorham** [comment]
Would you like me to try to implement something now that I understand the issue a little better?

**Comment by psonnera** [comment]
Yes, if you can spare a moment that would be fantastic. And I'd return supporting users, where I'm more useful and efficient. Thanks.

**Comment by jamorham** [comment]
This is included in the Feb 7th Nightly, please test and confirm. thanks

**Comment by psonnera** [comment]
@jamorham  Installed now. Will test for a few days. Again, thanks so much.

**Comment by psonnera** [comment]
image
I can't add treatments, they don't update in xDrip and don't upload to NS

**Comment by psonnera** [comment]
@jamorham working great. No treatments in Tidepool but CGM and BG are uploaded fine. Nightscout gets all data as expected. Thanks again.

**Comment by tolot27** [comment]
@psonnera, @jamorham It looks like this PR can be closed, right?

**Comment by psonnera** [comment]
@tolot27 it's working perfectly. Agree. Thanks!

**Comment by tolot27** [comment]
Merged with 94bee6e .

**Pull request closed without merging**
