### PR TITLE
xdrip to display openaps data

### PR DESCRIPTION
**Pull request by tzachi-dar**
This PR allows xdrip to display OAPS data (basal rate, iob, cob and last connected).

Still work in progress.
Currently work only when only when xdrip is uploading to NS.

Will add the option to get that data also when in NS follower mode.

### CODE REVIEW

**Comment by jroth-haj** [comment]
Will these data also be available to http://127.0.0.1:17580/pebble?
Will the data source also be local broadcast from AAPS?
That would be great!!!

**Comment by tzachi-dar** [comment]
Now also supports getting data in nightscout follower mode and printing the data to the screen.
See attached picture.

image

**Comment by old-square-eyes** [comment]
Would love to see this and also OAPS status on the xDrip Wear watchface.

**Comment by ahaarrestad** [comment]
Do you manage to get this pr to build on travis?

**Comment by tzachi-dar** [comment]
This was replaced by a newer pr.

**Comment by tolot27** [comment]
> This was replaced by a newer pr.

@tzachi-dar #1303 is the replacement, isn't it?

**Comment by tzachi-dar** [comment]
Yes, 1303 is the updated code.

**Pull request closed without merging**
