### PR TITLE
Add the US 14 days sensors with a SN that ends with E6.

### PR DESCRIPTION
**Pull request by tzachi-dar**
Still needs testing.

xdrip APK can be downloaded from: https://drive.google.com/file/d/1qlw9lSgDPYoF1dW0dbmfA3xjgpfCXp_w/view?usp=sharing

oop2 APK can be downloaded from:  https://drive.google.com/file/d/1vu3x4rvggb2k2rVlTc0kb1t4Yk_ULin5/view?usp=sharing

### CODE REVIEW

**Comment by psonnera** [comment]
Having a tester now, when should direct intent be used?

**Comment by kleenkanteen** [comment]
What does the title mean? Which US sensors are you talking about, libre 2? Also does xDrip+ currently use OOP2?

**Comment by gui-dos** [comment]
@kleenkanteen:

The title is not correct, indeed. It is the first byte of the sensor `patchInfo` which is `0xE6` for the newer US models instead of `0xE5`

**Comment by psonnera** [comment]
@kleenkanteen L1 14days US require OOP2 for xDrip+. L2 US is not supported (only L2 EU). For the title, as @gui-dos says.
Tested functional. More testing welcome.

**Review by jamorham — APPROVED** [review]

**Pull request merged**
