### PR TITLE
Tzachi libre2 improvements 2

### PR DESCRIPTION
**Pull request by tzachi-dar**
This replaces pr: https://github.com/NightscoutFoundation/xDrip/pull/1594

Still under testing.
Existing code:
    Show the per minute values of libre 2 as well.
    gap closing for libre bluetooth.
Coming next are:
    Filtering bad points.
    Data smoothing.

### CODE REVIEW

**Comment by DIajo** [comment]
HI, 
What I need to test your improvements (How can I download your version of Xdrip+ from 10 Feb.)?

**Comment by tzachi-dar** [comment]
Please try: https://drive.google.com/uc?id=1xzLEvZmeOIfRuQAN2ASrEs12sB1MH_6_&export=download

> HI,
> What I need to test your improvements (How can I download your version of Xdrip+ from 10 Feb.)?

Please download from: https://drive.google.com/uc?id=1xzLEvZmeOIfRuQAN2ASrEs12sB1MH_6_&export=download
Let me know how it goes.
You'll have to backup existing settings and database.  Then install new version, then restore from backup.

**Comment by Artemdrip** [comment]
what is working: 
1.The minute values on the Graph are visible (additional table of minute values could be very usefull)

issues:
1.Xdrip-widget does not want to be updated automatically (only when scanning)

questions:
1.How does the "gap closing for libre bluetooth" works? I can't see any difference.
2. When will you finish with "Filtering bad points" and "Data smoothing"?

**Comment by tzachi-dar** [comment]
> issues:
> -The minute values ​​are shifted upwards in y direction after a certain time
This is happening since the solution is using only the last calibration value.
> -The distance in x direction between 2 blood sugar points after bluetooth gape closing is sometimes 7
> minutes and not 5 minutes
> -bluetooth gape closing works only if the gape is smaller then 30 minutes
The bluetooth packets do not contain 8 hours of data only up to 45 minutes.
> -Xdrip-widget is not working
Is this something new with the branch?
> -can't choose any other language
> 
> questions:
> 
> * When will you finish with "Filtering bad points" and "Data smoothing (like by NFC-scanning)"?
Working on these things right now. I'll probably split this to two prs. so this one can go in first.

**Comment by tolot27** [comment]
@Artemdrip Please can you check the issues you mentioned in https://github.com/NightscoutFoundation/xDrip/pull/1640#issuecomment-813065798 with the new PR #1743?

This PR has been superseded by #1743.

**Pull request closed without merging**
