### PR TITLE
Companion app Dexcom One+

### PR DESCRIPTION
**Pull request by Navid200**
https://github.com/NightscoutFoundation/xDrip/discussions/3425

### CODE REVIEW

**Comment by jamorham** [comment]
Let me know if this is ready for merge

**Comment by Navid200** [comment]
I cannot test it myself because I don't have a One+.

But, can we not merge this and let the user who asked for it test it?
The change cannot break anything else, can it?  If it doesn't work, we can remove it.

**Comment by jamorham** [comment]
Are you confident on the package id?

**Comment by Navid200** [comment]
Sending you a message on Matrix (Gitter).

**Comment by Navid200** [comment]
Yes, as confident as I can be.

**Pull request merged**
