### PR TITLE
made mostly all prefs translateable

### PR DESCRIPTION
**Pull request by MasterPlexus**
Putting all hardcoded strings of prefs into strings.xml.
After acceptance by @jamorham  and merging, we could use Crowdin to made the proper translation steps.

Not sure, but I think also the wear strings.xml should be included in crowdin?

### CODE REVIEW

**Comment by tzachi-dar** [comment]
Good work.
I'm also working on translations.
I Will send soon a pr that prepares a lot of java strings for translation, so please don't work on that at the moment. (that is in java translating).

**Comment by MasterPlexus** [comment]
@tzachi-dar, so die you see at the moment an influence on your work at the moment? If not, then maybe @jamorham can merge my pull not so late, and if he agree so that strings.xml will be also for you in a clear state.

**Comment by tzachi-dar** [comment]
My pr is here: https://github.com/NightscoutFoundation/xDrip/pull/783
Since I was working mostly on the java code itself, then there should not be a problem.

Just wanted to make sure that if you are working on changing jave code, you will be aware of my work.

**Comment by MasterPlexus** [comment]
I'll made a diff check to see there is no overlapping (also in strings.xml). After that I'll give in your pr and my PR a statement. Latest this evening...

**Comment by MasterPlexus** [comment]
Checked the changes, and it is as I feared: the Strings.xml will be mixed hardly due to our work. So I would suggest to merge at first the pr https://github.com/NightscoutFoundation/xDrip/pull/783 from tzachi, after that I will then correct my pr to be in line.

@jamorham so at the moment don't merge my PR.I will mention you again when it is ready from my side.

**Comment by tzachi-dar** [comment]
I'm not sure that I foolow.
I only added things at the end of the file, you only added things at the
end of the file.
How did things mix?
One should easily be able to manually add them at the end of the file after
the next merge.

I think all directions should work.

**Comment by MasterPlexus** [comment]
We touched so stones the same strings, and there are also inclusions not at the end of the list..I had merge conflicts while I trying merging it locally, but this could be also as I go ahead with my.work (Wich I did not commit to my PR for now) before I see your message that I should stop.

**Comment by tzachi-dar** [comment]
I'll try to merge my work with you tonight, hoping things will be fine.

**Comment by MasterPlexus** [comment]
Ok, so I'll upload my latest commits to my PR, that you  have also the latest version.

**Comment by tzachi-dar** [comment]
Thanks

בתאריך יום א׳, 17 בפבר׳ 2019, 13:31, מאת MasterPlexus <
notifications@github.com>:

**Comment by tzachi-dar** [comment]
I have created another branch with my changes rebased over your changes.
It is in the tzachi-translation-merge branch.
Please let me know if you see it.

I can create a pull request to your PR, or we can simply wait for @jamorham to merge your pr, and then I'll recreate my pr.

**Comment by jamorham** [comment]
Please let me know the state of these two translation PRs, whether they are going to be integrated to a single PR to avoid merge conflicts?

Guidelines:
In general I would prefer smaller PRs for translations as they are easier to check and integrate. 
Also beware of changes to collector code will need to be replicated on wear.
New features and text I tend to avoid extracting the strings until the english is settled. I'm not sure the time period on this but at least a month I think. Of course string extraction often gets forgotten after that time.
Strings which are not presented to the user should not be translated as this creates additional overhead for each language for translation.

**Comment by tzachi-dar** [comment]
Please start with this pr, and I'll send my pr against the merged code. I think this will be simpler.

As for wear code:
Currently, they don't have the gs() function there so my script doesn't change them.
Can I assume that if the code compiles, it did not change anything that it shouldn't have (for example collector code)?

**Comment by MasterPlexus** [comment]
@jamorham :
> Please let me know the state of these two translation PRs, whether they are going to be integrated to a single PR to avoid merge conflicts?

I agree with tzachi. Please check and merge this pr. 

> Guidelines:
> In general I would prefer smaller PRs for translations as they are easier to check and integrate.

Agree, I'll made it in future in smaller pices.

> Also beware of changes to collector code will need to be replicated on wear.

I don touch at the moment dexcollector, but will have that in mind. But we have to have also in mind, that sometimes the texts should be not too big on wear compared to app... 

> New features and text I tend to avoid extracting the strings until the english is settled. I'm not sure the time period on this but at least a month I think. Of course string extraction often gets forgotten after that time.

Yes, I'm try to check every time how old the texts was established, and I think also one month should be ok. Please let me now if you agree also that I have included Pendic, Metrum and G6 settings. If not I will exclude them,but I think the texts looks like ok.

> Strings which are not presented to the user should not be translated as this creates additional overhead for each language for translation.

Thats clear. I try to exclude those kind of strings. For example where is visible that the texts are changed later by code (for example in buttons and so on) I leave them. Also for example the Log-level-Buttons I leave as they are, as they are very specific.

@tzachi-dar :
> I have created another branch with my changes rebased over your changes.
> It is in the tzachi-translation-merge branch.
> Please let me know if you see it.

Yes, could see it. 

> I can create a pull request to your PR, or we can simply wait for @jamorham to merge your pr, and then I'll recreate my pr.

I would say, it is better to let Jamorham merge them step by step, as otherwise the package will be too big.

**Pull request merged**
