### PR TITLE
Blucon: Pass patchUID and patchInfo to HandleGoodReading.

### PR DESCRIPTION
**Pull request by tzachi-dar**

### CODE REVIEW

**Comment by jamorham** [comment]
Has this been tested? Are there any implications for existing users etc?

**Comment by tzachi-dar** [comment]
This has not been tested on libre1 yet.
I've asked them again to test it.

**Comment by jamorham** [comment]
Should this be merged? Is it ready?

**Comment by tzachi-dar** [comment]
No, there are some small changes to this, but mainly it lucks testing of all 5 combinations:

New fw + us 14 days OOP
New fw + us 10 days OOP
New fw + us 10 days 
Old fw + us 10 days OOP
Old fw + us 10 days

**Comment by tzachi-dar** [comment]
This is replaced by
https://github.com/NightscoutFoundation/xDrip/pull/1286

**Pull request closed without merging**
