### PR TITLE
Updated it translation

### PR DESCRIPTION
**Pull request by mauriziocasini**
Added some new translation for italian language

### CODE REVIEW

**Comment by psonnera** [comment]
@mauriziocasini I'm also into it in Crowdin. Going very slowly for me.

**Comment by tolot27** [comment]
Thanks for your contribution. We translate xDrip using the semi-automated workflow system of [crowdin](https://crowdin.com). Please create an account at crowdin and add your suggestions there. Then, they will go through the translation workflow including proof reading.
Please report back here, when you are done and close this PR.

**Comment by Navid200** [comment]
@mauriziocasini Would you please respond to the questions?
Otherwise, if you are not interested in this any longer, would you please close the PR?
Thanks

**Comment by psonnera** [comment]
You can close it, I think we're up to date with Italian.

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
