### PR TITLE
Libre trend 7

### PR DESCRIPTION
**Pull request by tzachi-dar**
This code creates the libre trend for the entire sensor life.
It allows to show the libre trend graph for longer periods (see below for examples).
As a side result it also settes the sensor sn in all places except for libre alarm (where the data does not exist).
Tested for a few weeks with two sensors.

### CODE REVIEW

**Comment by tzachi-dar** [comment]
Here is an example of the improved dialog.
image

**Comment by gregorybel** [comment]
don't think it will break Blukon class.

**Comment by keencave** [comment]
Looks good for me too. I dont await any negative effects.

**Comment by jamorham** [comment]
Side note: Should `decodeSerialNumber` be moved to `LibreUtils` class?

**Comment by gregorybel** [comment]
would make sense!

**Comment by tzachi-dar** [comment]
decodeSerialNumber should move to libreutils. If it is ok, I'll do it in the next pr.

**Pull request merged**
