### PR TITLE
[wear] : Importing modifications made on the [app] application for Li…

### PR DESCRIPTION
**Pull request by lhplab**
Hello,

With MM2 FW0007 Libre 1 Europe I've never been able to get the 3 Following watches to work as collectors:
=> Misfit Vapour 2
=> Fossil Sport
=> Ticwatch C2
By looking at the code I've seen that the modifications made on the "app" tree were missing in the "wear" tree.
I've modified the files that I identified as involved in the new frame format.
I've tested my build on the Misfit and it works (no "endurance" tests performed at the moment.)

I hope this will help!
Don't hesitate to give me feedback or modify the code.
I Believe that I should have made a branch on my fork. I Don't know Git yet…

### CODE REVIEW

**Comment by parapenT1sta** [comment]
@jamorham Please merge this code. I know few people that are facing the same issue with Tomato 2 and firmware 0007.

**Comment by parapenT1sta** [comment]
@lhplab I think still not fix the issue with Firmware 0007, I tried a version compiled by other user with your commits but isn't working.

80639109_10221643635825168_1382691916956565504_o

81595802_10221643683746366_6372126201762283520_o

**Comment by lhplab** [comment]
Hello @parapenT1sta,
Sorry if it doesn't work for you. It's working well with my Misfit Vapour 2.
Did you install OOPAlgo on the watch?
I'm not at home at the moment (back at the end of next week) then I'll test with a Ticwatch C2 and Fossil Sport before dending them back to Amazon to be refunded.

**Comment by lhplab** [comment]
I don't know how to insert photos...

**Comment by lhplab** [comment]
I could post my apk if you want. What do you use to do this? Google drive?

**Comment by psonnera** [comment]
Drag and drop in your Github release

**Comment by lhplab** [comment]
@psonnera  @parapenT1sta I've published the build here : https://github.com/lhplab/xDrip/releases/tag/xDrip_wear_collector_20191218

**Comment by lhplab** [comment]
@parapenT1sta  on the watch I did go in the connectivity options / bluetooth and tried to connect the miaomiao several times and I also restarted the collector several times after having installed the apk on the watch (I don't know if it was needed or not).

**Comment by parapenT1sta** [comment]
@lhplab Sorry I didn't tell the whole information, people are using only Libre 1 with Firmware 0007, they say since the update the Wear Version doesn't collect Data from Libre 1 as was collecting before and maybe your fix is not for this. I am sorry for the miss understanding.

**Comment by lhplab** [comment]
Here are the printscreens:

**Comment by lhplab** [comment]
@parapenT1sta I'm using Libre 1 Europe.

**Comment by lhplab** [comment]
@parapenT1sta did you ensure to give the app the needed permissions on the watch? (localisation and sensors)?

**Comment by lhplab** [comment]
@parapenT1sta which version of OOP do you use? I'm using the version provided by miaomiao for Libre 2 (version fa218ef-de-libre2-sensors-2019.11.22 Built on: 1911221114. It works with Libre 1 Europe. I'm not using the version provided for Libre 1 US.

**Comment by parapenT1sta** [comment]
> @parapenT1sta did you ensure to give the app the needed permissions on the watch? (localisation and sensors)?

@lhplab I AM SO SORRY, the version you shared is working PERFECTLY FINE! Maybe something went wrong with the APK was shared with me.

**Comment by lhplab** [comment]
Nice to hear that!
Cool! 😊

**Comment by psonnera** [comment]
Ok, I messed it another time. Sorry @parapenT1sta!

**Comment by parapenT1sta** [comment]
> Ok, I messed it another time. Sorry @parapenT1sta!

Why do you say sorry?! You tried to help! That counts a lot!

@lhplab Thank you again, I am hoping to get this merged ASAP :)

**Comment by tzachi-dar** [comment]
I have read this pr, and it seems well, takes needed changes for libre2 + us sensors to the wear code path.
Can be merged in my opinion.
Thanks @lhplab for doing this.

**Comment by parapenT1sta** [comment]
> I have read this pr, and it seems well, takes needed changes for libre2 + us sensors to the wear code path.
> Can be merged in my opinion.
> Thanks @lhplab for doing this.

Thanks for your code review. Hopefully @jamorham  Can merge it.

**Comment by jamorham** [comment]
Are the files modified in the wear tree just exact copies of the current app tree versions?

**Comment by lhplab** [comment]
Hello @jamorham 

I've touched 7 files in my fork:

The following files are identical for app and wear:
=> **LibreAlarmReceiver.java**
=> **Models\Bubble.java**
=> **Models\LibreBlock.java**
=> **NFCReaderX.java**


I believe that I had issues with spaces, tabs or Windows/Unix CR/LF for **Models\Tomato.java** that seems to be different for app and wear in my local git project (maybe not on Github?) but they should be identical 

For the Following files I had to keep them different from the app version:
=> **Models\LibreOOPAlgorithm.java**
=> **UtilityModels\Intents.java**

**Comment by jamorham** [comment]
Thanks for this. I believe that this will be superseded by: https://github.com/NightscoutFoundation/xDrip/commit/c23915d2792187bca5aee60aa77b7d231569402a where the wear files are identical to the app versions and the code remains unified between app and wear for these portions. This is available in the Jan 9th nightly. Testing is appreciated.

**Comment by lhplab** [comment]
Hello @jamorham.
Thanks! I'll have a try soon. I will let you know when it's done.

**Comment by DavidAG2000** [comment]
> Thanks for this. I believe that this will be superseded by: [c23915d](https://github.com/NightscoutFoundation/xDrip/commit/c23915d2792187bca5aee60aa77b7d231569402a) where the wear files are identical to the app versions and the code remains unified between app and wear for these portions. This is available in the Jan 9th nightly. Testing is appreciated.

I've tested it and it doesn't work, while @lhplab it does work with a watch as a collector 😟

**Comment by lhplab** [comment]
@DavidAG2000 I Don't think that it will work but I tried to build a new apk based on the official release 2020.10.09. I can't test it now but Feel free to get it a try if you want… 
[https://github.com/lhplab/xDrip/releases/tag/MM2_FW0007_Wear_support_try20200109](url)

**Comment by DavidAG2000** [comment]
@lhplab Nope, not working. Only the first version 😔

**Comment by lhplab** [comment]
Hello @jamorham 
I've tried your last build and it works fine! :-)
Thanks!

@DavidAG2000 the watch works well as collector for me.
Are you sure that you've given xdrip the needed permissions on the warch (localisation, sensors),
Did you have several tries to connect the miaomiao with bluetooth?
Did you try to restart the collector on the watch ?

**Comment by DavidAG2000** [comment]
> Hello @jamorham
> I've tried your last build and it works fine! :-)
> Thanks!
> 
> @DavidAG2000 the watch works well as collector for me.
> Are you sure that you've given xdrip the needed permissions on the warch (localisation, sensors),
> Did you have several tries to connect the miaomiao with bluetooth?
> Did you try to restart the collector on the watch ?

Yes, I've given the needed permissions, and tried several times to connect the MM2 with Bluetooth. Also, I tried to restart the collector on the watch, but I got any results. The only version that worked fine for me was the first one you released 😕

**Comment by jamorham** [comment]
The changes between this branch and the master branch appear now to only be whitespace. I don't see any way that the code can behave differently. I am assuming that the problem @DavidAG2000 is experiencing must be something else. For example a signature mismatch between the wear app installed on the watch and the phone app if the wear app wasn't uninstalled when the phone app was changed perhaps.

**Comment by DavidAG2000** [comment]
> The changes between this branch and the master branch appear now to only be whitespace. I don't see any way that the code can behave differently. I am assuming that the problem @DavidAG2000 is experiencing must be something else. For example a signature mismatch between the wear app installed on the watch and the phone app if the wear app wasn't uninstalled when the phone app was changed perhaps.

Nope, that's not the reason. I have the same app on the phone as on the watch, have a look.
About the hardware I'm using, it's a Google Pixel 2 XL with Android 10.0, and a Fossil Gen 5 watch.

And as I said, the only version that worked for me was the first version that @lhplab released. And I'm not the only person who experienced that your 9th of December version didn't work. As you can see, on issue #840 I asked if your 9th of December version was working, but it didn't work for @dwpotter either. It must be something of the code of the released version.

Screenshot_20200115-151439
IMG_20200115_151523
dwpotter comment

**Comment by DavidAG2000** [comment]
@jamorham The only version that worked for me, as for others was this one: 

https://github.com/lhplab/xDrip/releases/tag/xDrip_wear_collector_20191218

**Comment by lhartje** [comment]
I can confirm that I was able to get data from my MM2 via the wear collector with version 99c6d71-2020.01.09 (Samsung S9 running Android 9 and a Fossil Gen5 Carlyle HR watch running WearOS 2.12).

Thanks!

**Comment by DavidAG2000** [comment]
Hi again, @jamorham 

I have to say that sometimes the watch acts weird as collector, and sometimes (I do not know why), it doesn't work as collector.

Watch this example:
In the images you can see that the phone is not getting any information, and the watch seems that is working as collector, but it doesn't. The reason of that is that you can see that is getting the measurements through the phone (as it says that the Uploader is getting the information).

And another times, as I said, is not working as collector, unlike @lhplab first version, which did 🤷‍♂️
https://github.com/lhplab/xDrip/releases/tag/xDrip_wear_collector_20191218

IMG_20200116_160909
Screenshot_20200116-160859

I will keep updating.

**Comment by edwardowen78** [comment]
Hey guys, I really appreciate all the work you are all doing. If I can help test in anyway, please let me know.  I presume this hasn't been merged yet but looking forward to its release. @lhplab how did you install OOP algorithm onto your watch? (apologies for asking same question in other thread but this one is newer). I have the APK already on my phone.

**Comment by psonnera** [comment]
adb install -r youroopname.apk
directly on the watch

**Comment by edwardowen78** [comment]
Forgive me I'm a little out of the loop. does that mean with fossil 5, I have to activate developer option, and setup ADB session over Bluetooth or can I do something like side loading.

**Comment by psonnera** [comment]
I usually do that with my PC, yes, sideloading after enabling developer mode on the watch, use the charging USB cable.

**Comment by lhplab** [comment]
Hello @edwardowen78 BTW I'm now using the official version from @jamorham because the watch now works as collector.

**Comment by DavidAG2000** [comment]
Hi again @jamorham, I can confirm that your version is working for my Fossil Gen 5 (working as collector).

Thank you so much for work, and for helping us 🙂

**Comment by DavidAG2000** [comment]
> Forgive me I'm a little out of the loop. does that mean with fossil 5, I have to activate developer option, and setup ADB session over Bluetooth or can I do something like side loading.

Having a Fossil Gen 5, as me, you have the option as well to debug through Wi-Fi, so you don't have to connect the watch to a computer with a USB cable 😀

**Comment by DavidAG2000** [comment]
> Hey guys, I really appreciate all the work you are all doing. If I can help test in anyway, please let me know. I presume this hasn't been merged yet but looking forward to its release. @lhplab how did you install OOP algorithm onto your watch? (apologies for asking same question in other thread but this one is newer). I have the APK already on my phone.

By the way, I didn't manage to install the OOP algorithm on my phone/watch, the app didn't work on my phone. I'm using a Google Pixel 2 XL with Android 10 (as far as I'm concerned, OOP algorithm doesn't work on Android 10). Send me a message or reply to this if someone manages to install it correctly. Thank you.

**Comment by edwardowen78** [comment]
I'm using the Samsung s8 with Android 9 and oop is definitely working for me on that. Shame about Android 10 causing issues, hope you get a fix soon.

**Comment by edwardowen78** [comment]
@lhplab Am I right in thinking that if I have 16th Jan xdrip build and OOP on s8 (running Android 9) and fossil gen 5, I should be able to get watch as collector (with Oop)? 

If so, that's absolutely brilliant, pretty much everything I was hoping for. Thanks for all the help

**Comment by DavidAG2000** [comment]
> @lhplab Am I right in thinking that if I have 16th Jan xdrip build and OOP on s8 (running Android 9) and fossil gen 5, I should be able to get watch as collector (with Oop)?
> 
> If so, that's absolutely brilliant, pretty much everything I was hoping for. Thanks for all the help

What makes you think that if the watch works as collector without OOP, it won't with it?

**Comment by edwardowen78** [comment]
@davidag2000 well I haven't managed to get the watch working as a collector at all yet. I'm just asking generally if I'm doing everything right and that I'm not missing something.

**Comment by DavidAG2000** [comment]
> @DavidAG2000 well I haven't managed to get the watch working as a collector at all yet. I'm just asking generally if I'm doing everything right and that I'm not missing something.

The key is to go to the watch settings -> Connectivity -> Bluetooth -> Search for available devices -> Connect to your MM2 (it will make a "virtual" connection, as it won't say connected). Maybe your phone will make a sound confirming that the watch is paired with your MM2. Now your watch will be able to work as collector.

Hope that this helps 🙃

**Comment by edwardowen78** [comment]
Thanks David, I will give it a try now.

**Comment by edwardowen78** [comment]
I have managed to install Oop algorithim to my fossil gen 5 and it is also now working as a standalone collector. The last piece to this puzzle is getting night scout setup. Thank you all very much with your help on this.

**Comment by tolot27** [comment]
@lhplab Can this PR be closed? There are no significant changes left.

**Comment by dwpotter** [comment]
I think so
Yes 
Thanks,
Dave

**Comment by tolot27** [comment]
Fixed already with c23915d and merged into [Nightly build 9th Jan 2020](https://github.com/NightscoutFoundation/xDrip/releases/tag/2020.01.09).

**Pull request closed without merging**
