### PR TITLE
Remove the scanning with MAC addresses filter since it does not work with TicWatch pro.

### PR DESCRIPTION
**Pull request by tzachi-dar**
See https://github.com/NightscoutFoundation/xDrip/issues/840

We have made many experiments to find what the issue is.
It seems that for this version of the watch, scanning with an IP filter does not work.
The code always returns with a scanerror of timeout.

When scanning without the filter, the scan does succeed.

Since we verify the ip addresses when the scan finishes, I have removed the filter all together.

Other options might be use a flag for setting this filter or try to detect this specific watch, but I think that the first method is not good enough since it will be a bad user experience and for the second option I'm not sure what is the list of watches that I should give.

### CODE REVIEW

**Comment by parapenT1sta** [comment]
I can confirm that works with Ticwatch E (Android 8.0.0) and MiaoMiao 1.

**Comment by jamorham** [comment]
I assume this PR should say MAC address rather than IP address.

Can you confirm which software version is running on the Ticwatch Pro that has been tested with this PR?

thanks.

**Comment by tzachi-dar** [comment]
Obviously, this is a mac addresses and not an IP addresses.

**Comment by parapenT1sta** [comment]
@jamorham I tested with a Ticwatch E with Android 8.0.0 which I was facing the same issues as Ticwatch Pro and with this fix everything went back to normal as before the Feb. 4th 2019 release.

**Comment by jamorham** [comment]
The Ticwatch Pro can scan for mac addresses. 

I'm unable to reproduce the issue with TicWatch Pro Build number `PWDD.190617.007` Wear OS version `2.8` Google play services `19.2.75`  System version `H`, Patch level `June 2019` using the standard published xDrip+ Sept 21st Nightly.  (all latest versions afaik)

Settings `Use Scanning = enabled` & `Trust Auto-Connect = disabled`

It seems to work fine as is on TicWatch Pro.

```
09-23 20:49:24.597  5076  5076 D ScanMeister: stopScan called from: Scan stop
09-23 20:49:24.716  5076  5076 D ScanMeister: stopScan called from: Scan start
09-23 20:49:24.716  5076  5076 D ScanMeister: startScan called: hunting: EF:A7:89:12:D0:FF null
09-23 20:49:26.815  5076  5076 D ScanMeister: Found a device: EF:A7:89:12:D0:FF  rssi: -90  -> MATCH
09-23 20:49:26.816  5076  5076 D ScanMeister: stopScan called from: Got match
09-23 20:49:26.817  5076  5076 D ScanMeister: stopScan stopped scan
09-23 20:49:27.318  5076  5076 D ScanMeister: Processing callbacks for EF:A7:89:12:D0:FF SCAN_FOUND
09-23 20:49:27.318  5076  5076 D ScanMeister: Callback: DexCollectionService
09-23 20:49:27.815  5076  6594 D ScanMeister: stopScan called from: Scan stop
```

**Comment by parapenT1sta** [comment]
@jamorham From the feedback that I got from members of diabet1cos.pt, Ticwatch and any WearOs Watch uing Android H version is working perfectly fine. The worst is any WearOS watch using android 8.0.0 version, like Ticwatch E ou S version. E2 or S2 have Android H and they are OK.

**Comment by tzachi-dar** [comment]
Two small comments:
1) The issue was seen by a few other people and reported on https://github.com/NightscoutFoundation/xDrip/issues/840.

2) We are still testing this fix, trying to understand if it is better to remove the filter at all, or put a filter that is empty.

**Comment by jamorham** [comment]
So does this issue only affect Ticwatch E ?

Removing the filter will break scanning on AOSP based Android 8.1
Using an empty filter will break on Qualcomm based Android 9+

On Android 8.0 I would expect that Scanning can simply be disabled via the preference option. Has that been tested? Collector may need to be restarted to be sure.

**Comment by tzachi-dar** [comment]
I think that we are left with the option to set this by a UI preference.
Does anyone see something better?

**Comment by parapenT1sta** [comment]
> I think that we are left with the option to set this by a UI preference.
> Does anyone see something better?

Be able to choose on the watch / phone "Alternative Pair mode", I think it's a good idea.

**Comment by parapenT1sta** [comment]
@jamorham With a new version sent by @tzachi-dar the feedback so far: https://github.com/NightscoutFoundation/xDrip/issues/840#issuecomment-536193471

**Comment by jamorham** [comment]
@parapenT1sta Could you get the model names of the affected models for E and S via `adb shell` use `getprop ro.product.model` - I am expecting they are just `Ticwatch E` and `Ticwatch S` but to be absolutely certain this should be verified. We can use this to enable conditional code to work around issues with those models.

**Comment by jamorham** [comment]
See https://github.com/NightscoutFoundation/xDrip/commit/f2c33e3e550c0f3b38f11559392199e43940a657 for what I think is a much better way to implement this which wont break scanning on other devices as it is selective for these two Ticwatches.

I'm interested to know whether this works, it is included in the Sept 30th nightly which is available now.

**Comment by parapenT1sta** [comment]
> See [f2c33e3](https://github.com/NightscoutFoundation/xDrip/commit/f2c33e3e550c0f3b38f11559392199e43940a657) for what I think is a much better way to implement this which wont break scanning on other devices as it is selective for these two Ticwatches.
> 
> I'm interested to know whether this works, it is included in the Sept 30th nightly which is available now.

I wrote on Gitter, that is working perfectly fine with Ticwatch E, I don't have a Ticwatch S to test. Other devices I reported had Android H and in fact I don't know if they were having issues with the newer versions of xDrip.

Do you want me to ask in my group who is using WearOS watchs and what Android version do they have? To add all with Android 8.0.0 or lower to the list?

**Comment by tzachi-dar** [comment]
Issue was solved on another pr.

**Pull request closed without merging**
