### PR TITLE
Linear Trapezoid Equations to Close out #1200

### PR DESCRIPTION
**Pull request by peeyes-dev**
As noted in #1200, equations has been verified by @stephencmorton. Took me a while to figure out how to submit a pull request. Sorry about that.

Please note Android Studio issues a warning that "public LinearTrapezoidInsulin" could be become "private LinearTrapezoidInsulin". Please do the needful as needed.

### CODE REVIEW

**Comment by gruoner** [comment]
@peeyes-dev @jamorham @stephencmorton
commit 45dea78 has an error: subtracting onset from max (in constructor line 29) is wrong.
**a single injected dose (1 IE) is "active" for time between "onset" and "t3". the sum (area / integral under the activity curve) is exactly 1.0** - right? Not? lets discuss why not....

here is my wxmaxima script to plot a novorapid curve (the one active before MultiInsulin Patch was applied) with a single peak at 75min after ONSET (here onset is 0)
t1:75;
t2:75;
t3:180;
max:2/(t2-t1+t3);
IOB1(x):=1-max/(2*t1)*x*x;
IOB2(x):=1+max*t1/2-max*x;
IOB3(x):=max/(2*(t3-t2))*(t3-x)^2;
IOB(x):=if (0<=x and x<t1) then IOB1(x) else if (t1<=x and x<t2) then IOB2(x) else if (t2<=x and x<t3) then IOB3(x) else 0;
dIOB1(x):=''(diff(IOB1(x), x, 1));
dIOB2(x):=''(diff(IOB2(x), x, 1));
dIOB3(x):=''(diff(IOB3(x), x, 1));
dIOB(x):=abs(if (0<=x and x<t1) then dIOB1(x) else if (t1<=x and x<t2) then dIOB2(x) else if (t2<=x and x<t3) then dIOB3(x) else 0);
wxplot2d([IOB(x)], [x,-50,t3+30]);
wxplot2d([dIOB(x)], [x,-50,t3+30]);
sum(dIOB(x), x, 0, t3);
when u subtract onset while calculating "max", u will get an lower max, resulting in a sum under activity curve lower that 1.0

the next error is at line 38:
subtracting onset from t1 is wrong as all t's are still based / biased / offset'ed by "onset" in config file "insulin-profiles.txt"
same error at line 39/40/41 and even in calculateActivity - **now the equations are broken!**

**Please:
Take your time and use wxmaxima to understand and plot the equations AND compare the curves with those active before MultiInsulin Patches. I know, it is not that easy to understand maxima formula / code but it is a scientific tool to write formal correct equations**

@jamorham 
PLEASE have a look at those equations and code and compare the new result with the "old" behaviour.
This new code leaves multi insulin broken......

**Comment by peeyes-dev** [comment]
> 
> 
> @peeyes-dev @jamorham @stephencmorton
> commit [45dea78](https://github.com/NightscoutFoundation/xDrip/commit/45dea784b2032524c55e72b97a56446b804ecd43) has an error: subtracting onset from max (in constructor line 29) is wrong.
> **a single injected dose (1 IE) is "active" for time between "onset" and "t3". the sum (area / integral under the activity curve) is exactly 1.0** - right? Not? lets discuss why not....
> 
> here is my wxmaxima script to plot a novorapid curve (the one active before MultiInsulin Patch was applied) with a single peak at 75min after ONSET (here onset is 0)
> t1:75;
> t2:75;
> t3:180;
> max:2/(t2-t1+t3);
> IOB1(x):=1-max/(2_t1)_x_x; IOB2(x):=1+max_t1/2-max_x; IOB3(x):=max/(2_(t3-t2))*(t3-x)^2;
> IOB(x):=if (0<=x and x<t1) then IOB1(x) else if (t1<=x and x<t2) then IOB2(x) else if (t2<=x and x<t3) then IOB3(x) else 0;
> dIOB1(x):=''(diff(IOB1(x), x, 1));
> dIOB2(x):=''(diff(IOB2(x), x, 1));
> dIOB3(x):=''(diff(IOB3(x), x, 1));
> dIOB(x):=abs(if (0<=x and x<t1) then dIOB1(x) else if (t1<=x and x<t2) then dIOB2(x) else if (t2<=x and x<t3) then dIOB3(x) else 0);
> wxplot2d([IOB(x)], [x,-50,t3+30]);
> wxplot2d([dIOB(x)], [x,-50,t3+30]);
> sum(dIOB(x), x, 0, t3);
> when u subtract onset while calculating "max", u will get an lower max, resulting in a sum under activity curve lower that 1.0
> 
> the next error is at line 38:
> subtracting onset from t1 is wrong as all t's are still based / biased / offset'ed by "onset" in config file "insulin-profiles.txt"
> same error at line 39/40/41 and even in calculateActivity - **now the equations are broken!**
> 
> **Please: Take your time and use wxmaxima to understand and plot the equations AND compare the curves with those active before MultiInsulin Patches. I know, it is not that easy to understand maxima formula / code but it is a scientific tool to write formal correct equations**
> 
> @jamorham
> PLEASE have a look at those equations and code and compare the new result with the "old" behaviour.
> This new code leaves multi insulin broken......

@gruoner. Thanks for checking my code. Before I submitted the pull request and I did the testing in Excel spreadsheet as part of my code development and provided equations and curves which were independently verified by @stephencmorton. Based on that @jamorham pulled the code in. 

Thank you for providing the wxMaxima script. I used it as a starting point and implemented the equations that I derived and implemented into pull request code. Since the equations in your script were different than what I have implemented, rather than re-rechecking your equations, I re-did the script with my implementation but I could not reproduce what you saw. 

I derived and coded. For novorapid in the insulin profile.txt, onset = 10 and i am using that value along with my equations.

I have attached a PDF file with the wxMaxima session and I do not see what you are seeing. The sum is adding to spot on 1.0, which is what I expected. The plots also show exactly what I expected. Having said that, please do verify my wxScript and my implemented equations and see whether I missed anything as an independent check. As far as I could see, I could not see anything amiss and I stand by my equations and code, unless proven otherwise.

My wxMaxima code

onset:10;
t1:75;
t2:75;
t3:180;
max:2/(t2-t1+t3-onset);
IOB1(x):=1.0-0.5*(x-onset)*(x-onset)*max/(t1-onset);
IOB2(x):=1.0+0.5* max*(t1-onset)-max*(x-onset);
IOB3(x):=0.5*(t3-x)*(t3-x)*max/(t3-t2);
IOB(x):=if (0<=x and x<onset) then 1.0 else if (onset<=x and x<t1) then IOB1(x) else if (t1<=x and x<t2) then IOB2(x) else if (t2<=x and x<t3) then IOB3(x) else 0;
dIOB1(x):=''(diff(IOB1(x), x, 1));
dIOB2(x):=''(diff(IOB2(x), x, 1));
dIOB3(x):=''(diff(IOB3(x), x, 1));
dIOB(x):=abs(if (onset<=x and x<t1) then dIOB1(x) else if (t1<=x and x<t2) then dIOB2(x) else if (t2<=x and x<t3) then dIOB3(x) else 0);
wxplot2d([IOB(x)], [x,-50,t3+30]);
wxplot2d([dIOB(x)], [x,-50,t3+30]);
sum(dIOB(x), x, 0, t3);

[novorapid.pdf](https://github.com/NightscoutFoundation/xDrip/files/4916461/novorapid.pdf)

**Comment by gruoner** [comment]
u'r plots seems to be correct - have to check u'r equations to see if they are equivalent.....
i will come back in a hour or two.

**Comment by gruoner** [comment]
OK; finished my analysis and u'r equations seems to be correct under two conditions (must be kept into account when using)

- the T's (t1 to t3) are now based on time 0 (before / mine was based on onset). as all insulin profiles in "insulin_profiles.txt" are still the same, i checked the activity curves of novorapid, actrapid and insulatard and this "timeshift" will not get a big effect on BG-prediction. The "old" / legacy calculation has a zero onset and 75min until peak, so it was and still is different from the changed and different from the new calculation.

- IOB now starts with injected dose right after injecting - so noone can see when insulin becomes active (esp. on long acting profiles like levemir). As this change is just relevant for displaying IOB (and doesn't have any effect on BG-prediction) it is a matter of personal preference

IOB is still discontinuous but this doesn't matter  until all T's and onset are multiples of timeslize......

So the only effect of this PR is to shift the T's to timebase 0 instead of onset.

**Pull request merged**
