### PR TITLE
more Chinese strings

### PR DESCRIPTION
**Pull request by jizhongwen**

### CODE REVIEW

**Comment by jizhongwen** [comment]
added more Chinese translation

**Comment by jamorham** [comment]
Please submit via crowdin: https://crowdin.com/project/xdrip

thanks

**Comment by tolot27** [comment]
@jizhongwen Did you add your changes via crowdin? Also, please try to avoid reformating the xml (different indent).

**Comment by tolot27** [comment]
@jizhongwen Thanks again for your kind contribution. We translate xDrip using the semi-automated workflow system of [crowdin](https://crowdin.com). Please create an account at crowdin and add your suggestions there. Then, it will go through the translation workflow including proof reading.
Please report back here, when you are done and close this PR.

**Comment by tolot27** [comment]
I've compared this PR with the current crowdin translation and made changes when necessary.

**Pull request closed without merging**
