### PR TITLE
added Samsung Galaxy S9+

### PR DESCRIPTION
**Pull request by PoweRGbg**

### CODE REVIEW

**Comment by jamorham** [comment]
Does this mean you have tested this successfully? Was this with OB1 collector or the original one?

**Comment by PoweRGbg** [comment]
Yes - I'm using it for more than 12 days and capture rate is above 97%. It's with the OB1 collector

**Comment by jamorham** [comment]
If it is with OB1 you should add OB1 to the mode column, see the other examples towards the end.

**Comment by jamorham** [comment]
I assume this is no longer valid in reference to: https://github.com/NightscoutFoundation/xDrip/issues/663

**Comment by PoweRGbg** [comment]
My S9+ is not updated to the latest version, so no connection issues

**Comment by Navid200** [comment]
@PoweRGbg Hi,
My understanding is that all Android phones can be used to run xDrip unless their operating system is extremely old (before Android 4.4?).  That is what I tell everyone on the facebook group.  
There was a time we maintained these files of phones that were compatible with xDrip.  But, I don't believe we do that any longer.

Would you please tell me what you think?
If you agree, can we close this pull request?

Thanks

**Comment by PoweRGbg** [comment]
This PR is 3 years old :) closing it

**Pull request closed without merging**
