### PR TITLE
G6 backfill prior to start AAPS fix copied to wear

### PR DESCRIPTION
**Pull request by Navid200**
I have just copied the mods (f98d57b and 6f7c366) to the corresponding wear files.

I have no way of testing this as I have no Android wear device.

Please feel free to edit, or tell me to edit.

Fixes https://github.com/NightscoutFoundation/xDrip/issues/1890

### CODE REVIEW

**Comment by tolot27** [comment]
@Navid200 Thanks for taking this over. I've added the corresponding commit hashes to simplify the review.

As long as we have no common library module for app and wear, we have to increase the code duplication, unfortunately. :unamused:

**Comment by Navid200** [comment]
@tolot27 Thanks

**Review by tolot27 — APPROVED** [review]
Files are identical and build succeeds.

LCTM

**Comment by jamorham** [comment]
Just to add, I don't think this will have any practical effect regarding resolving any particular issue as AAPS isn't running on wear.

**Comment by Navid200** [comment]
@jamorham In that case, please let's not merge it.

**Comment by Navid200** [comment]
@jamorham There is a comment in the open issue.
I am going to respond to the comment and state there should be no need to edit the wear files.
And, I am also going to ask the individuals to confirm the issue has been resolved and hopefully close the issue in a week or so.

**Comment by jamorham** [comment]
There might be some combination of starting/stopping the sensor from elsewhere with wear running as a collector that could result in duplicated data but I don't think xDrip running on the phone would allow that data to be emitted but it is still worth ensuring that the wear collector doesn't even request the data in the first place. This assumes that the Sensor record is kept up to date on wear as well but either way I would normally just intend to keep the collector code in sync between app and wear. Its designed to work like that with identical files.

**Comment by Navid200** [comment]
Understood.  Thanks

**Pull request merged**
