### PR TITLE
Added tests for Nighscout Follow Entry - getTimestamp

### PR DESCRIPTION
**Pull request by ahaarrestad**
* Added tests for NightscoutFollow Entry - getTimestamp
* Minor updates in DateUtil to remove warnings in code

@jamorham hope you can find time to take a look and merge if ok.

### CODE REVIEW

**Comment by jamorham** [comment]
What effect will adding: `Locale.getDefault()` do to the date formatting vs how it is now?

**Comment by ahaarrestad** [comment]
Nothing. If you are not comfortable adding it, I can remove it.... but the formatting wants a Locale specified.

**Comment by ahaarrestad** [comment]
@jamorham removed the default locale setting... back to the way it was.

**Comment by jamorham** [comment]
So is specifying `Locale.getDefault()` the same as not specifying it? Eg that is what the existing signature actually does. Should we be specifying a Locale?

**Comment by ahaarrestad** [comment]
Almost the sane. In effect the same. Leaving it like it was is less change which i know is preffered :-) work fine and build is green. I easily get carried away ckeaning up code :-)

**Review by jamorham — APPROVED** [review]
Looks good, thanks for keeping the change set minimal.

**Pull request merged**
