### PR TITLE
fix bluereader bug and add sweetreader

### PR DESCRIPTION
**Pull request by AdrianLxM**

### CODE REVIEW

**Comment by AdrianLxM** [comment]
@SGS-Industry, could you please test this? thans

**Comment by SGS-Industry** [comment]
The embedding of the sweetreader name works. it can flow into the series software

**Comment by jamorham** [comment]
@AdrianLxM thanks for spotting that casing bug. Is this something which should now be merged?

**Comment by SGS-Industry** [comment]
Yes, please merge this...

---- von unterwegs gesendet ----

**Comment by AdrianLxM** [comment]
Seconding @SGS-Industry: Yes please.

**Pull request merged**
