### PR TITLE
Stats round percentage

### LINKED ISSUE #1496: Statistic: the percentage sum is not equal to 100%
See screenshot below:
The 3 values are truncated (not rounded), so the sum equals 98% in this screenshot and not 100%
My suggestion would be to round the High and Low percentages to the nearest integer value  and calculate the "in range value"  with 100% complement ... 

High=5/283=1.77 => 2%
Low=8/283=2.83 => 3%
In=100-(2+3) = 95%

Screenshot_20201105-064728_xDrip+

### PR DESCRIPTION
**Pull request by Philoul**
Proposal to fix #1496

### CODE REVIEW

**Review by tolot27 — COMMENTED** [review]
@AdrianLxM Please can you test this? It looks good to me. The inRange is reduced slightely at the cost of belowRange and aboveRange. This is fair-minded.

**Comment by AdrianLxM** [comment]
I'll do this weekend 🙂

Just a note: we do have the same statistics in the History, and the status line (widget/home screen).

**Comment by tolot27** [comment]
> Just a note: we do have the same statistics in the History, and the status line (widget/home screen).

@Philoul Please can you patch the status line in the widget/home screen as well?

**Comment by Philoul** [comment]
@tolot27 I think it's already done in my second commit and StatsResult.java file (Adrian told me that his message was a reminder for him...)
I'm waiting for feedback from @AdrianLxM and if there still remains other modifications or files to patch, I'll of course update the PR...

**Comment by tolot27** [comment]
You are right. Currently, I'm testing it.

**Review by AdrianLxM — APPROVED** [review]
Looks good to me.

Sorry that there is a bit technical debt / redundancy there. There is a copy of StatsResult in the wear module. (It was copied instead of using a common module and diverged).

I'd ignore it for now as it is not used on wear at all.

**Comment by tolot27** [comment]
I'v updated the description to [automatically link to the issue](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by Philoul** [comment]
@AdrianLxM I compared both files and there are many differences between them...
If you want I can update (even if not used in Wear) the percentage calculation of Wear file to be consistent, but I don't know what could be impacts if we replace the wear StatsResult by the main App version...
May be it's better to not change Wear file in this PR and change for a common module in another PR with more verifications/validations (I don't know how to do that myself)

**Comment by AdrianLxM** [comment]
@Philoul I misspoka and it seems it is used for the watchfaces. I don't have a watch to test at the moment. Please update it on wear as well.

**Comment by Philoul** [comment]
Percentation calculation for in/high/low range updated in Wear StatsResult file too.

**Review by tolot27 — APPROVED** [review]

**Comment by jamorham** [comment]
I will get this merged shortly.

**Pull request merged**
