### PR TITLE
Send Display Glucose (smoothed) via REST to NS

### PR DESCRIPTION
**Pull request by AdrianLxM**

### CODE REVIEW

**Comment by jamorham** [comment]
Okay this PR looks pretty good. Can I confirm a few points:

1) Have you tested this to confirm it works?
2) I assume the switch to control the behavior defaults to off?
3) I assume those strings are already defined and make sense in this context?

**Comment by AdrianLxM** [comment]
1. yes
2. yes
3. If you are referring to the "keys" in the json uploaded to NS.

**Comment by jamorham** [comment]
I meant the preference description strings.

**Comment by jamorham** [comment]
I'm concerned that this doesn't have time related safety checks like there is with `InjectNoise` for example:

```
 final BgReading bgReading = this;
        if (JoH.msSince(bgReading.timestamp) > Constants.MINUTE_IN_MS * 20) {
```

`getDisplayGlucose()` is going to work on the 2 most recent readings which might not be what is actually in `BgReading` `this` which would result in problematic behavior if that happened.

The display glucose also contains a noise value so we could also later merge the two methods once we are satisfied each is working correctly.

**Comment by AdrianLxM** [comment]
Ad Question 3): Yes, those are the Strings used in the settings for sending Display Glucose in the inter-app settings.

Ad safety checks: I used the same logic as in BgSendQueue->local broadcast, where this isn't guarded either except for a simple check for `null` being returend from `getDisplayGlucose()`. I thought you did have a solution for out of sync/order data already in there?

**Comment by jamorham** [comment]
Yes, I think it could run in to the same type of problem as cited in issue https://github.com/NightscoutFoundation/xDrip/issues/126 (which is going to require some restructuring to fix if it is appropriate)

As this new smoothing is off by default and a vast majority of people the data is going to be processed as it arrives in the correct sequence and with each reading spread out then I think this should be fairly safe to merge this and we can see what happens with it operationally.

**Pull request merged**
