### PR TITLE
Add Afrezza, Apidra, Levemir, Basaglar and Tresiba profiles

### PR DESCRIPTION
**Pull request by TheConen**
This is NightscoutFoundation#1388 with the merge conflicts resolved.

Since #1388 seems to be dead, I resolved the merge conflicts and created this PR.

### CODE REVIEW

**Comment by jonjonr6** [comment]
If you commit to making these changes would you consider adding the profile for the relatively new ultra fast lispro insulin  Lyumjev (Messrs. Eli Lilly).

Here is link to manufacturer's data (profile shown at sect. 12 "Clinical Pharmacology").
[https://uspl.lilly.com/lyumjev/lyumjev.html#pi](url)

Regards,
Jonathan Rees

**Comment by doc77** [comment]
I read #1388 and felt compelled to comment. I fully use the Insulin Profiles and have been since they were first released in nightlife. I use Novolog (Novorapid) and Tresiba. In the Insulin Profile I use Novorapid and Toujeo because Tresiba is not a choice. Needless to say I have to do a lot of calculations in my head!
The addition of a Tresiba profile may not replace some of those necessary calculations but it will certainly reduce them.

Can xdrip (or any other software) predict things like exercise, sickness, or any of the things we must consider when calculating a bolus? Of course not. Xdrip is not an artificial pancreas. 

But xdrip has been helping me for almost  20 of my 52 years of diabetes. Without it I doubt if I could maintain a normal a1C.

Please merge this PR and make xdrip better, not perfect.

**Comment by ANDREAPIPPI** [comment]
I absolutely agree!
Andrea

**Comment by desperatelydoing** [comment]
Same.
Glen

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jamorham** [comment]
If this PR were just additive in terms of insulin profiles I would be very happy to merge it. My concern is the changes to existing profiles which could impact existing users unexpectedly.

Can you please explain the changes where this has been done?

**Comment by TheConen** [comment]
I just took the changes from #1388 and resolved the merge conflicts - I think everything regarding these changes and the sources for the changs in the profiles has already been discussed there. 

I'm perfectly happy to remove the changes to existing insulin profiles if that will get this finally merged. #1388 has been open for over 3 years, intensely discussed and approved, yet nothing happened - so I decided to take matters into my own hands. After all, #wearenotwaiting - and as an Apidra user, I want to be able to choose the insulin I use in xDrip+.

**Comment by ANDREAPIPPI** [comment]
[jamorham] I'm a little confused.
You say you're concerned that changing insulin profiles "could impact existing users unexpectedly."
I don't agree with this, because the changes are not so big that they can produce such effects.
There are simply adjustments to some flex points, not completely changing curves.
On the contrary, I think that the greater precision should be appreciated by those who, with the support of their Endo, use xDrip+ to find their best insulin therapy.
Am I wrong or am I missing something?
Andrea  :-)

**Comment by jamorham** [comment]
Okay. I'm just asking for explanation of the changes to existing profiles as that is not present in this PR yet.

Personally I have never seen what I think of as an accurate insulin action curve and the information from manufacturers doesn't seem to reflect any reality and I expect things differ for different people but I understand that this is a useful feature to people even so and am happy to help people improve it.

The issue here is that if a user is using a particular action curve and then this PR changes it then that user might see different results without realizing that the curve has been changed. @ANDREAPIPPI says that these changes are not so significant but that is exactly the sort of information I'm asking for in relation to this PR before we make a change that impacts existing users it needs to be handled carefully.

I would like to merge the PR but there needs to be justification in it. It isn't enough to reference previously submitted PRs, please state exactly what this PR does and the reasons for the change and where there are changes to existing behavior how that is expected to impact on users. This isn't a feature I use and so I'm not so familiar with what could go wrong with these changes.

**Comment by ANDREAPIPPI** [comment]
TheConen, could you please show us a comparison of the old/new action curves of  Novorapid, Lantus and Toujeo that you proposed in your first post?
This will give a clearer idea of the real variations and their possible influence on practical results for the users.
Thank you.
Andrea

**Comment by TheConen** [comment]
I removed all changes to existing insulin profiles so that this PR now only adds new insulin profiles.

> please state exactly what this PR does

It adds new insulin profiles for Afrezza, Apidra, Levemir, Basaglar and Tresiba

> and the reasons for the change 

because as a user of one of these insulins (Apidra) I want to be able to choose that Insulin when entering treatments in xDrip+

> and where there are changes to existing behavior how that is expected to impact on users. 

Users have more insulin types to choose from.

> It isn't enough to reference previously submitted PRs

This PR shouldn't even exist. The only reason this PR exists is because #1388 has been abandoned. All your questions have already been answered in #1388 by @jordy-de-koning, including scientific sources and manufacturer information regarding the data for the insulin profiles right in the very first post. Feel free to delete this PR and merge #1388 instead - but do merge one of them.

**Comment by doc77** [comment]
@jamorham  I can vouch for a real world effect of the lack of this PR. 
I have to use the Toujeo profile instead of a Tresiba profile. I take Tresiba in the morning and I'm sometimes not fully awake.  Since Toujeo has a much shorter half life than Tresiba when I glance at xdrip for my insulin curve ( the green shaded area) I am sorely misled. The result has been AM hypos. By the time I shower and get dressed my bg is crashing. This could be avoided if the correct insulin curve for Tresiba was present in xdrip.

**Review by jamorham — APPROVED** [review]

**Comment by jamorham** [comment]
Thanks for this, please feel free to re-add the the insulin types which had modifications. Those modifications just need to be justified in terms of their impact to existing users so that we can be sure as we can be that it wont cause problems. Overall I have some ideas for how this feature could be improved. The structure of how this works is not ideal in terms of flexibility and user choice and I would have preferred to have had it implemented initially in a different way.

Please see https://github.com/NightscoutFoundation/xDrip/blob/master/CONTRIBUTING.md#contributing-patches-to-xdrip to understand the sort of things that will be evaluated when reviewing a PR.

**Comment by Navid200** [comment]
After this PR has been merged, this is what you see on a screen resolution of 2160 x 1080, and there is no way to scroll down to see Fiasp.
So, something is wrong with the layout.

Screenshot_20231106-230751

**Comment by TheConen** [comment]
@Navid200 Please test again with #3177

**Comment by doc77** [comment]
@TheConen @Navid200 I use a pretty big phone, Samsung Note 20, and the whole list only shows if I am in landscape mode.

**Comment by TheConen** [comment]
@doc77 Does that also happen with #3177?

**Comment by doc77** [comment]
I don't know. I just downloaded the one in the nightlies

**Comment by jonjonr6** [comment]
I'm not sure what happened to the other "missing" insulin profiles. Lyumjev [ultra-rapid lispro (URLi)] was mentioned a while back but is still on the waiting list. Can it be included? (I could digitise the plots if that helps).

PDF of profile info extracted from manufacturer's data as linked below:
[Lyumjev_profile.pdf](https://github.com/NightscoutFoundation/xDrip/files/13300714/Lyumjev_profile.pdf)

Link to manufacturer's data (see section 12 "Clinical Pharmacology":
[https://uspl.lilly.com/lyumjev/lyumjev.html#pi](url)

**Comment by TheConen** [comment]
Lyumjev is not one of the insulins that was in #1388, hence why it was not in this PR. I'm happy to open a new PR for Lyumjev if needed.

**Comment by jonjonr6** [comment]
Thanks for your reply. The original request was issue #1561 from Frediabetics. This was closed when Lyumjev was added to a table of requested profiles in #1898 which is still open. There was an issue concerning the validity of the profile data source. I'm sorry if I've "hijacked" this PR.
I have now added this request, along with the data source to #1898.

**Pull request merged**
