### PR TITLE
Date picker for SiDiary export

### PR DESCRIPTION
**Pull request by AdrianLxM**
This adds a Date picker to the SiDiary-csv export function. This way it will no longer export everything form the "beginning of times".

### CODE REVIEW

**Comment by AdrianLxM** [comment]
@MasterPlexus could you please test this. That would be great!

**Comment by MasterPlexus** [comment]
@adrianlxm, yes indeed, will check it tomorrow.

**Comment by MasterPlexus** [comment]
Tested and worked fine. also the Code has no point to commend from my side. I would say could be merged.
Not sure about the rules here, but I see that I could do a review in the Github. Should I or better leave it.

**Comment by AdrianLxM** [comment]
Back to WIP: feature request - adding the time of the last export would be a great addition.

**Comment by AdrianLxM** [comment]
@MasterPlexus I've added the functionality of preselecting the day of the last export as you wanted. Could you please test it? Thanks

**Comment by MasterPlexus** [comment]
@adrianlxm Test is running. I'll come back tomorrow to see that the correct date was set.

**Comment by MasterPlexus** [comment]
Tested, and works properly as expected.

**Comment by AdrianLxM** [comment]
Thanks @MasterPlexus. I also tested it again and it worked as expected with one more day :)

**Pull request merged**
