### PR TITLE
consistent writing and typo fixes of English resource strings

### PR DESCRIPTION
**Pull request by tolot27**
This PR addresses many points of #1554

### CODE REVIEW

**Comment by tolot27** [comment]
Will check the wear strings this evening. Afterwards, I'll remove the draft flag.

**Comment by tolot27** [comment]
Is the base language en-gb or en-us? I suspect en-gb.

**Comment by tolot27** [comment]
I've double checked the strings by visual inspection and a word processor. Maybe, it is necessary to adjust the translations as well, especially for 4dfdcfd.

**Comment by tolot27** [comment]
@jamorham Feel free to cherry-pick any of the commits if you don't want to merge all at once.

**Comment by jamorham** [comment]
Hi thanks. Can you confirm that you've checked the execution of the positional argument changes to the format strings within the app? They look okay to me but as its effectively a code change I would like confirmation of testing. I believe positional formatting is supported down to the minimum sdk level but I haven't checked that to confirm.

**Comment by tolot27** [comment]
Barcode renaming is suggested in #1151, too.

**Comment by tolot27** [comment]
> Hi thanks. Can you confirm that you've checked the execution of the positional argument changes to the format strings within the app? They look okay to me but as its effectively a code change I would like confirmation of testing. I believe positional formatting is supported down to the minimum sdk level but I haven't checked that to confirm.

I've tasted that the positional arguments work. Argument indices (=positional arguments) are supported since very early Java versions long before Android was developed.

**Comment by Navid200** [comment]
I don't see invite_follower in the strings file.  So, how is the first change (android:text="@string/invite_follower") going to work?

**Comment by tolot27** [comment]
> I don't see invite_follower in the strings file. So, how is the first change (android:text="@string/invite_follower") going to work?

Commit 1c1b9725 contains it.

**Review by jamorham — APPROVED** [review]

**Pull request merged**
