### PR TITLE
Blukon: baulk on unexpected sensor changes

### PR DESCRIPTION
**Pull request by gregorybel**
Reviews are welcomed as I cant test it

### CODE REVIEW

**Comment by dabear** [comment]
One other possibility is to use footer crc as unique identifier for the sensor? We know that body is static, but header contents (and header crcs) change infrequently.

**Comment by jamorham** [comment]
@tzachi-dar is right. I think the `pratelimit` needs to be completely removed as we have to check serial number every time.

**Comment by gregorybel** [comment]
actually yes good catch from @tzachi-dar but the timer is force resetted after time is going backward so after a sensor change, Serial number will be requested again. so latest 5min later.

We can for sure request each time, this is not battery optimised but at least we have more security.

**Comment by jamorham** [comment]
@gregorybel I think you understand the code flow here better than me, if the timer is reset then we would expect one bad reading if there is then a sensor serial mismatch?

**Comment by gregorybel** [comment]
I checked code again and in fact sensor time is requested every 3 hours, so it could be that we catch new sensor after 3 hours.
So, I simply removed serial decode timer, which anyway doesn't cost that much battery, as it is decoded by phone (I thought we need to request it from sensor over BT).

**Comment by tzachi-dar** [comment]
LGTM.

**Pull request merged**
