### PR TITLE
Lower Voltage B warning level

### PR DESCRIPTION
**Pull request by Navid200**

### CODE REVIEW

**Comment by Navid200** [comment]
This is an example of what people see these days:
xDrip-Status-Screenshot-2024-10-27-08-09-21

**Comment by Navid200** [comment]
This change will lower the trigger so that we see red only if the voltage is lower by 25.

**Comment by jamorham** [comment]
This is probably okay but can you provide your rationale for this change?

**Comment by Navid200** [comment]
I used this as a reference: https://github.com/NightscoutFoundation/xDrip/discussions/3408#discussioncomment-9002235

**Review by jamorham — APPROVED** [review]

**Pull request merged**
