### PR TITLE
Last update for Amazfitservice

### PR DESCRIPTION
**Pull request by Klaus3d3**
JamOrHam, please take care of this PR. Last time i tried this, it ended into a mess. :-)

### CODE REVIEW

**Comment by jamorham** [comment]
Well this is a bit of a messy PR but the actual changes look fairly simple and I can probably extract those. Can you remind me which watches this supports? Thanks

**Comment by Klaus3d3** [comment]
This is for the Amazfit Pace and Stratos. It now offers support for the watchface i wrote.
The old service only supports the widget on the watch wich is quite messy to use.
With the watchface we have the value on a transflective AOD. 
There are already a lot users, who are forced to use my xdrip fork wich is quite old.

**Comment by Klaus3d3** [comment]
Yeah, and sorry for the messy code. :O

**Comment by Klaus3d3** [comment]
Should i do something here? If so, it might gets even messier. :-)

**Comment by jbm76** [comment]
Yesssss  jamorham... Please!!!

The only watchface in Amazfit to see the gluc9se...is made by klaus3d3 😊😊... And his versión of xdrip!! And it's too old a version...

please we would like you to update xdrip with the changes indicated

thank you very much in advance for the work you do

BEST regards

**Comment by caiobarreto** [comment]
any news?

**Comment by jbm76** [comment]
> 
> 
> any news?

No news about it ....

To see our glucose, amazfit pace / stratos users will still have to use the Xdrip version created by klaus3d3 on September 9, 2018 ...

We hope that soon there is news ... that seems  is pending review and hopefully soon there will be good news!

many thanks in advance to those who are working for it

**Comment by jamorham** [comment]
As the author knows, this PR is a bit of a mess. It includes unrelated changes and has conflicts with the current branch.

I plan to manually extract the goodness out of it but it isn't a simple quick process which is why there has been a delay in processing this.

**Comment by jbm76** [comment]
Effectively Jamorham, you are absolutely right, it seems somewhat messy and difficult to implement. 

I hope you can get the good out of the code and make the amazfit service in xdrip, also work for Pace / Stratos users, every time we are more diabetic with it.

 We trust in your work and hopefully soon we can try a new change in xdrip.💪💪💪. 

we will be attentive to the news.
Many thankssss

**Comment by jamorham** [comment]
The 23th Feb nightly should contain these changes. Please test and confirm it works. Thanks.

**Comment by Klaus3d3** [comment]
Hey, thanks for your work. Seems to work good for me.
But i have a different problem with this nightly wich seems not amazfit related.

All warnings are gone and i can't set new. After setting them up and testing they don't get saved.
The alarm list is empty again.

**Comment by jbm76** [comment]
> 
> 
> The 23th Feb nightly should contain these changes. Please test and confirm it works. Thanks.

Grande Jamorham !!! Fantastic!!!

Thanks for your work adapting it!!! I tried it tonight and it worked well !!!

Finally we can see in our AMAZFIT PACE our glucose with the latest version of xdrip + with all its improvements ...

Thank you very much again

P.d:Now I'm looking to see how the low glucose alerts arrive

**Comment by jbm76** [comment]
> ist is empty again.

The same happened to me! Yesterday when I installed it did not let me create alerts, but I do not know very well why, but this morning he let me create them without any problem !!!!!

**Comment by rbordalba** [comment]
Hi @jamorham , I installed the nightly build from the 23rd and I tested it on my **Amazfit Stratos** (The Amazfit service from @Klaus3d3 worked for both Pace and Stratos model). While it worked in the Pace from @jbm76 , it didn't work in my Stratos  :(  
The watch just crashes when using the latest Xdrip nightly, so I had to go back to the old Xdrip. I don't know what could be the problem ..

is there anything I can do to help finding the issue?

Thank you for the effort! :D

**Comment by Klaus3d3** [comment]
I doubt this is really caused by xdrip. This could only be an issue within the watches service. Please restart both phone and watch and try again.

**Comment by rbordalba** [comment]
I restarted both the phone and watch and now I don't get that crash, however I still don't receive the BG data on the watchface (even though I have Amazfit service enabled in Xdrip).

**Comment by Klaus3d3** [comment]
Wich version of the watch app are running?

**Comment by rbordalba** [comment]
If I'm not mistaken I have version 0.02 (not 0.03..) 
I will update it tonight and try again, this could be the problem.

**Comment by Klaus3d3** [comment]
Between the last two versions is'nt any real change only a bugfix, but somehow some people have issues with the last. I could'nt figure out whats the cause of this, yet. So try both if the last one does'nt work.

**Comment by jamorham** [comment]
Please let me know if all is well and I can close this PR, @Klaus3d3  thanks

**Comment by rbordalba** [comment]
I updated to the latest watchface (0.03) and it worked now with my Amazfit Stratos :D 

Thanks @jamorham  and @Klaus3d3  for your awesome work!

**Comment by Klaus3d3** [comment]
For me its all fine with the Amazfit Service. 
I still have the Warning issue but i think its not related to to this PR

**Comment by jamorham** [comment]
closing as integrated manually

**Pull request closed without merging**
