### PR TITLE
Tzachi translation merge

### PR DESCRIPTION
**Pull request by ErickRosas**
I am presenting here a completely new translation to Spanish as a replacement for the old one.
Everything has been included (that can be attached from the strings.xml English resource file)

It does not affect any other functionality and it has been thoughtfully tested with 3 native Spanish speakers in their phones
(samsung, Huawei and LG) after doing a self signed apk using Android Studio 4.0.1 and xDrip+ 2020.10.01.

No other files had to be changed since this is a simple xml file.

I am also proposing to create a New Pull Request Tag named simply "Translations" :)

[strings-es.zip](https://github.com/NightscoutFoundation/xDrip/files/5333063/strings-es.zip)

### CODE REVIEW

**Comment by tzachi-dar** [comment]
I'm not sure I understand what you are doing here.
This is an old pr...

**Comment by tolot27** [comment]
@ErickRosas Thank you for your effort. Please create a pull request against master containing the relevant parts of your `strings-es.xml` compared to https://github.com/NightscoutFoundation/xDrip/blob/master/app/src/main/res/values-es/strings-es.xml.

**Comment by ErickRosas** [comment]
Ok. Done.

Thanks
Sincerely
Emiliano Llano Díaz

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tolot27** [comment]
Closed, because created against the wrong branch.

**Comment by ErickRosas** [comment]
Understand.
Wouldn’t it be better to create a new branch called “translations”?
😊


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tolot27** [comment]
@ErickRosas

>Wouldn’t it be better to create a new branch called “translations”?

Typically, you create a new branch in your fork (based on the most recent master branch) for every feature or bug you are working on. You can name it like you want, but giving the branch a meaningful name like `translation-es` is useful. Then you open a PR. After it gets reviewed and merged, you can delete your branch.

**Comment by ErickRosas** [comment]
Ok. Understood

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ErickRosas** [comment]
Mathias:

Now I really do not understand.
How come the Spanish resource file is just the old (incomplete and erroneous) one?
Did I miss something in the process?
I thought that everything was settle and ready to go.
Great disappointment since it was really a lot of work and hours and hours of testing involving 3 people.

Maybe I need more detailed instructions on how to create a branch to include this complete translation.

Thanks for your help and patience.
Sincerely
Emiliano Llano Díaz


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Erick elrojo<mailto:compuvtt@hotmail.com>
Sent: Tuesday, October 6, 2020 1:40 PM
To: NightscoutFoundation/xDrip<mailto:reply@reply.github.com>
Subject: RE: [NightscoutFoundation/xDrip] Tzachi translation merge (#1460)

Ok. Understood

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tolot27** [comment]
@ErickRosas You have to create a new branch in your fork which is based on master.

Do the following:
```
git remote add upstream https://github.com/NightscoutFoundation/xDrip.git
git checkout master
git pull
git fetch upstream
git merge upstream/master
git push
```

Than create a new branch with `git checkout -b translation_es`. Replace the string_es.xml or patch it. Commit your changes and push them back to your fork using `git push --set-upstream origin translation_es`. Afterwards, you can create a new PR using the webinterface.

But @jamorham recommends using [Crowdin](https://crowdin.com/project/xdrip/es-ES).

**Comment by ErickRosas** [comment]
Hi there Mathias,

Thank you for your time and response.
Try to do as you told me. Hope everything went OK this time.

Sincerely
Emiliano Llano Díaz


________________________________

**Pull request closed without merging**
