### PR TITLE
Code cleanup - home menu event handlers

### PR DESCRIPTION
**Pull request by Lupum1001**
This is the 2nd half of PR https://github.com/NightscoutFoundation/xDrip/pull/2159
There aren't any functional changes present in this PR.
As I was working on the other one, I noticed that we were using 3 separate code conventions for different menu items: "onclick" methods, 'if' statement lists, and switch-cases. There was a linting warning about the use of switch-cases, so I figured I should just make everything consistent.

I've re-arranged things so they all use the "onclick" convention. That was suggested to be the preferred method of the three, and most of the other options were doing it that way anyway:
https://github.com/NightscoutFoundation/xDrip/pull/2159#issuecomment-1141179360

### CODE REVIEW

**Review by tolot27 — COMMENTED** [review]
Did you test every event handler and can you confirm it is still working?

**Comment by Lupum1001** [comment]
So the menu items affected are:

- Import/Export features -> Export Database
- Import/Export features -> Restore Database
- Import/Export features -> Export CSV (SiDiary format)
- Speak Readings
- Resend glucose to watch
- Open Settings on Wear
- Reset Wear DB


The import/export ones all appear to visibly work, as well as the "Speak Readings" toggle. I don't have an android watch attached to my test emulators, but I was able to confirm with breakpoints that the final 3 all trigger as well. I checked on an API 19 device and an API 30 device.

image

**Review by tolot27 — APPROVED** [review]
LGTM

**Comment by Lupum1001** [comment]
Just pulled in the latest changes from master and did a quick sanity check on the build. The menu items, including the new cloud backup still work fine.

**Comment by Lupum1001** [comment]
@jamorham this is ready for final inspection/merging when you've got a minute.

**Review by jamorham — APPROVED** [review]

**Pull request merged**
