### PR TITLE
RouteFindeTest improvements

### PR DESCRIPTION
**Pull request by ahaarrestad**
Minor refactoring of test to utilize Truth a bit better and ease reading.

### CODE REVIEW

**Comment by ahaarrestad** [comment]
@jamorham added a minor formatting change to a test

**Comment by jamorham** [comment]
This looks like it just have reformatting and static import changes and no functional changes to the tests. Is that right?

**Comment by ahaarrestad** [comment]
@jamorham Correct. No functional changes, just a bit better use of Google.Truth :-)

**Comment by ahaarrestad** [comment]
@jamorham any plans on merging this pullrequest?

**Pull request merged**
