### PR TITLE
Remove G5 from status page header

### PR DESCRIPTION
**Pull request by Navid200**
This is what the status page will look like after this:  
Screenshot_20240603-075232  Outdated - please see next post
 
I forgot about this one in my previous PR: https://github.com/NightscoutFoundation/xDrip/pull/3506

### CODE REVIEW

**Comment by Navid200** [comment]
Screenshot_20240603-084816

**Comment by jamorham** [comment]
I don't want to make changes that could potentially include trademarks unless absolutely necessary. I'm fine with removing G5 though.

**Comment by Navid200** [comment]
These headings have been fluid ever since One came along.  Since then, there have been even more.
And there will be more coming soon.
So, my hope is that we can use a heading that remains intact as new devices come along.
So, I hope you accept the update I have made to this PR to address your concern.

If not, please let me know and I will just remove G5.

**Review by jamorham — APPROVED** [review]
Yes this is fine now

**Pull request merged**
