### PR TITLE
Don't request to read Libre 2 multiple blocks beyond the 43rd

### PR DESCRIPTION
**Pull request by gui-dos**
With a Libre 2 you cannot read beyond the 43rd FRAM block therefore when you read three blocks at a time in `multiblock` mode you have to read the final block singly.

### CODE REVIEW

**Comment by tolot27** [comment]
@gui-dos Thanks for you contribution. Please can you add a unit test to your PR? We've started implementing [code coverage](https://app.codecov.io/gh/tolot27/xDrip) and our goal is to not introduce issues while enhancing xDrip.

@tzachi-dar Please can you have a look at this PR?

**Comment by tzachi-dar** [comment]
Just by looking at the code, it seems correct. I still would like to test it.
@gui-dos will this allow for multi block reads with libre 2?

**Review by tzachi-dar — APPROVED** [review]
I have checked this code with a libre2 sensor in both modes and it works well.
Should be merged.

**Comment by tolot27** [comment]
@tzachi-dar @gui-dos Please can you implement a unit test at least for the `doInBackground` function or provide some test data? It is really important that we test our implementations also in an automated manner.

**Review by jamorham — APPROVED** [review]
Looks like it should work. Thanks for testing the implementation.

**Pull request merged**
