### PR TITLE
Make sure that xdrip will not have two sets of points on the same time (libre)

### PR DESCRIPTION
**Pull request by tzachi-dar**
Fix the issue that is widely explaind in https://github.com/NightscoutFoundation/xDrip/issues/752

### CODE REVIEW

**Comment by tzachi-dar** [comment]
Still being tested.

**Comment by tzachi-dar** [comment]
Tests have passed, can be merged.

**Comment by jamorham** [comment]
By all means make `getForPreciseTimestamp(long timestamp, double precision, boolean lock_to_sensor)` public but beware that `precision` is likely to be refactored to `long` type in the future. 

Don't remove the helper signature that has `long` as the precision type as this is what it is supposed to be long term.

**Comment by tzachi-dar** [comment]
Changed precision to long right now.
Still needs final testing.

**Comment by tzachi-dar** [comment]
`I wonder what the failure in tests means:
com.eveningoutpost.dexdrip.Models.SensorSanityTest > checkLibreSensorChangeTest FAILED
    com.google.common.truth.Truth$AssertionErrorWithCause at SensorSanityTest.java:90

We don't seem to have such a test, and SensorSanityTest.java only has 46 lines.

**Comment by jamorham** [comment]
You can ignore that test failure it is due to some other changes and is due to differences between local and CI test parameters. I will try to resolve that today. 

So this PR now conflates two different change sets. The one you originally intended to resolve this specific issue and now the refactoring to long type for `getPreciseTimestamp()` which means it is spilling over in to things like the medtrum collector. 

This isn't what I wanted but as the changes are still fairly minimal and should be harmless I will accept it anyway. The smaller and more isolated a changeset is, the easier it is for me to accept for merging.

**Pull request merged**
