### PR TITLE
Shorter lines on the "Speak Readings" page

### PR DESCRIPTION
**Pull request by Navid200**
| Subject                      | Detail |
|------------------------|----------------------------------------------------------------------------------------------------------|
| Why do we need this? | So that small devices can show the number of minutes <br/> See the images after the table.  <br/>  fixes: https://github.com/NightscoutFoundation/xDrip/issues/553 |
| Is there a work-around? | No |
| Are there any side-effects to this fix? | The title text now will appear in the summary with a smaller font | 
|Tests | This has been tested, on a small device, using the Android studio virtual devices. |

The following shows the current release on a screen with a resolution of 240X400.
Before

After the fix, this is what the same page will look like on the same device:
115640297-9de1db80-a2e4-11eb-9fce-e054a914202f

### CODE REVIEW

**Comment by tolot27** [comment]
This PR likely fixes it for English only. I suggest to find a general solution, i.e. by allowing text-wrapping.

**Comment by Navid200** [comment]
Even if we fix the problem for English only first, that is a step forward as opposed to the current situation.   For a 3-year old issue, I would consider that a step forward.

I agree with you that there may be other solutions.  I strongly disagree that we should wait for perfection.  I prefer to offer users a solution even if it is not perfect.

I don't see why other languages cannot find alternative phrases, like I did for English.

**Comment by tolot27** [comment]
> Even if we fix the problem for English only first, that is a step forward as opposed to the current situation. For a 3-year old issue, I would consider that a step forward.

Problem here is that the change of the English source strings invalidates all corresponding translations and none of the translators know why and that the should sorten the translation.

> I agree with you that there may be other solutions. I strongly disagree that we should wait for perfection. I prefer to offer users a solution even if it is not perfect.

IMHO, it has nothing todo with perfection. You provided a workaround, not a solution. A solution would be to either wrap the text automatically or shrink the size automatically. Both are simple solutions. Please can you propose either of these solutions? In Android Studio you can easily switch the display language and screen sizes for testing.
 
> I don't see why other languages cannot find alternative phrases, like I did for English.

That's sometimes impossible because English text is about 15% shorter than German (for instance) in terms of string length. Other translations are much longer than English even if the the shortest translations are used.
Also, nobody can test it because a screen size of 240X400 is very rare.

**Comment by Navid200** [comment]
I spent a few days on this trying to figure out a way to reduce the font size.  I was not able to.
 jamorham stated, in the original issue, that he ran into trouble when he attempted to solve the problem.

The suggested work-around solves the problem for English.  It does not solve the problem for all languages.
Therefore, it is an improvement.  The original issue was raised by someone who used the English language.

If this is merged, no one will be stopping anyone from finding a way to reduce the font size or make it wrap.  So, a better solution can be found later.  
But, we have waited 3 years for that.  I am happy for it whenever it comes.  But, please let's not object to a work-around.

**Comment by Navid200** [comment]
> Also, nobody can test it because a screen size of 240X400 is very rare.

I just used the virtual device in Android Studio to test a size of 240X400.    Why wouldn't everyone be able to do the same?

**Comment by tolot27** [comment]
> I just used the virtual device in Android Studio to test a size of 240X400. Why wouldn't everyone be able to do the same?

Because translation happens at Crowdin and not in Android Studio.

**Comment by tolot27** [comment]
Most of the problems can be solved easily if a higher API level would be used. We will see if jamorham will merge this PR.

**Comment by Navid200** [comment]
I moved the text, from title to summary.  With no change to the text itself, the following is the result.
Screenshot_1619053121


Is this better?  Please note that the font size is now quite small (summary).
If this is better, how can I change an open pull request without closing it and opening a new one?

Or, is the text too small now?

**Comment by nightscout-ricsi** [comment]
I prefer:
If changes by ()
Frequency in minutes ()

**Comment by Navid200** [comment]
@nightscout-ricsi To be correct, we cannot call it frequency.  We can call it period, cycle, how often, ...  But, not frequency.  Frequency, by definition, is the number of occurrences per unit time.  While what this is is how often something happens.
The two are related, but, not the same.   f = 1/ Period

**Comment by nightscout-ricsi** [comment]
> @nightscout-ricsi To be correct, we cannot call it frequency. 
Agree, but it is much easier to understand, with this name. Maybe we should change the unit, ex. speak per hour.
But maybe "period of speak" is better. I am not a native english speaker.

**Comment by tolot27** [comment]
> If this is better, how can I change an open pull request without closing it and opening a new one?

Meanwhile, you should know how to update a PR. 😄

**Comment by Navid200** [comment]
> > If this is better, how can I change an open pull request without closing it and opening a new one?
> 
> Meanwhile, you should know how to update a PR. 😄

Yes, that was a while ago.
I can spend time and figure out how to change the slider.  It is used in several places in xDrip and all have larger text.  So, that would be a good solution.  
But, it will take quite some time for me to figure it out.

**Comment by tolot27** [comment]
I've assigned this PR to me and will have a look during this weekend. Hopefully, I can suggest a solution.

**Comment by Navid200** [comment]
I have reverted the wordings to the original.
But, I have moved the text to the summary, which has a smaller font and does wrap.  
The numerical value being adjusted is still shown in the title.
For what it looks like, please view my last message of April 21 above.

**Comment by Navid200** [comment]
@jamorham That's exactly what I have done.
However, that's not what I had originally.  That's why there are so many commits even though the change now is only very simple.
I can close this PR and open a new one only containing moving the content from the title to the summary, which is what this is  right now.

**Comment by Navid200** [comment]
https://github.com/NightscoutFoundation/xDrip/pull/2076

**Pull request closed without merging**
