### PR TITLE
Tzachi tidepoll2

### PR DESCRIPTION
**Pull request by tzachi-dar**
Fix issues that caused tidepool data not to be uploaded.

In the case of an object with bad data, tidepool drops the entire request, and this causes that data stops going up to tidepool.

First two  commits were based on issues found for a local user.

The last commit is based on the tidepool specs. See https://github.com/NightscoutFoundation/xDrip/issues/842#issuecomment-520195276

### CODE REVIEW

**Comment by tzachi-dar** [comment]
@pazaan can you take a look at it?

**Comment by jamorham** [comment]
Thanks for this. In the wild was it a case of negative values causing a problem?

**Comment by pazaan** [comment]
@jamorham: in the Tidepool server logs I checked, it was negative CGM values, but any of these conditions would return a 400 status.

**Comment by tzachi-dar** [comment]
There were two issues for that specific user. One was bg of -26 (caused by libre with 0.012 reading).
The second is the user wanted to enter bg reading of 119, but for some reason entered this as a bolus of insulin with value=119 (which is also too big).

**Comment by LongboatAline** [comment]
@tzachi-dar could we do some sanity checking on input data? For example ask back if a single dose of insulin exceeds previous tdd...

**Pull request merged**
