### PR TITLE
WIP: follow treatments stored in Nightscout

### PR DESCRIPTION
**Pull request by tolot27**
Addresses #1231 and #735 partially.

ToDos:

- [ ] interface hint should not be shown on data import
- [ ] avoid reuploading
- [ ] download treatments only since last received treatment
- [ ] apply removals (from NightScout or other sources) within certain amount of time (i. e. 30 minutes)

### CODE REVIEW

**Comment by tolot27** [comment]
How to avoid reuploading it to the same NS instance?

**Comment by dubidrubi** [comment]
Hi @tolot27,

Will this change fix https://github.com/NightscoutFoundation/xDrip/issues/1231 ?

Running the latest xDrip version still doesn't allow to sync treatments between followers using NS. Any treatment added from xDrip appears in the NS with xdrip tag and doesn't sync to other xdrip devices in the sync group.

**Comment by tolot27** [comment]
@gruoner Do you have any ideas to address the problems mentioned above?

**Comment by gruoner** [comment]
> @gruoner Do you have any ideas to address the problems mentioned above?

i didn't recognized issues with reuploading - i use this feature for quite a year

for the other 3 ToDos i can't imaging the problem; i didn't get any problems with "interface hints" or "download problems". Maybe i'm using it another way.
But as i didn't remove treatments in xdrip master nor follower and i didn't use xdrip's or nightscout's reporting feature (i use nightscout reprter) i did not get any problems with removing treatments (for now)

**Comment by tolot27** [comment]
@gruoner Does this PR work for you as well?

**Pull request closed without merging**
