### PR TITLE
Database size on status page

### PR DESCRIPTION
**Pull request by Navid200**
This PR adds a new item to classic status page, the database size.  
It removes the phrase "downgradable to" from the same status page.  

| Before | After |  
| ------- | ------|  
| xDrip-Status-Screenshot-2024-11-05-21-53-00 | xDrip-Status-Screenshot-2024-11-05-23-07-26 |

### CODE REVIEW

**Comment by jamorham** [comment]
I think this is very messy what you're doing here. You're trying to use asynchronous features synchronously and creating a lot of weight for something that really doesn't need to be that complicated. See the new utility method I have provided for this. I suggest completely reworking this PR to just use that: https://github.com/NightscoutFoundation/xDrip/commit/53507c76c13de04a02c93359583492173e288e7e

**Comment by Navid200** [comment]
Thanks you so much.
Will be done.

**Comment by Navid200** [comment]
Thanks for the guidance.
It should be good now.
Thanks

**Comment by olorinmaia** [comment]
@Navid200 What is the use-case that benefit of knowing database size?

**Comment by Navid200** [comment]
@olorinmaia If you have been using xDrip for years, the database may contain data you will never need inside xDrip any longer.  Keeping data in xDrip corresponding to 20 years ago is not necessary.  
  
I welcome suggestions as to what could be the cause of this:  https://github.com/NightscoutFoundation/xDrip/issues/1280 
In the meantime, I would suggest to everyone to avoid allowing their database to unnecessarily grow.   
  
Being able to see the size of the database can be useful for deciding when you may want to do some cleanup.

**Comment by olorinmaia** [comment]
Thanks for some info regarding this. If database cleaning is necessary, is this the way or is there other methods? 
https://navid200.github.io/xDrip/docs/Backup/SaveDaily.html
I mean setting Glucose retention to e.g. 365.

**Comment by Navid200** [comment]
> Thanks for some info regarding this. If database cleaning is necessary, is this the way or is there other methods? https://navid200.github.io/xDrip/docs/Backup/SaveDaily.html I mean setting Glucose retention to e.g. 365.

Thanks for that link.  I will need to update that.

Yes, setting glucose retention to a value like 365 is a way to limit the size.

**Pull request merged**
