### PR TITLE
add relative SD in stats page

### PR DESCRIPTION
**Pull request by AdrianLxM**
Metric used in papers like http://care.diabetesjournals.org/content/40/7/832 e.g.

### CODE REVIEW

**Comment by jamorham** [comment]
Is this ready for merge?

**Comment by AdrianLxM** [comment]
Yes please :)

**Comment by doc77** [comment]
Will this essentially be the calculated %CV?

**Comment by AdrianLxM** [comment]
@doc77 exacly. That's why it says "CV" ;)

**Comment by doc77** [comment]
@AdrianLxM    That would be extremely helpful. Thank you!

**Pull request merged**
