### PR TITLE
Fixed serious error in russian translation

### PR DESCRIPTION
**Pull request by mclaudt**
"Carbs Per Unit" was translated as "grams of carb in one **carbohydrate** unit (XE - хлебная единица)", not "grams of carb, covered by one **insulin** unit".

### CODE REVIEW

**Comment by tolot27** [comment]
Hi Mike, thank you for you PR. I've accepted your crowdin request. Please can you make the change [their](https://crowdin.com/translate/xdrip/all/en-ru?filter=basic&value=0#q=carbs_per_unit)? Then it will go to the proofreader workflow.
I would prefer a shorter text, too.

**Comment by mclaudt** [comment]
Thanks, @tolot27!
It seems that colleagues from crowdin have just already approved this version here https://crowdin.com/translate/xdrip/7/en-ru#276
In that case the length for "carbs_per_unit" is not longer than already existing length for "insulin_sensitivity_glucose_drop_per_unit". 
They have also concluded that length is needed to highlight the important difference between these two parameters. It's easy to get the two mixed up.

**Comment by tolot27** [comment]
@mclaudt As long as it fits onto smaller screens, it will be okay.

**Comment by mclaudt** [comment]
I have tested these parameters locally on emulators, even 240x320 devices look fine. 

image

**Comment by mclaudt** [comment]
After updates of translations, carbs_per_unit key seems to be missing in Russian translation. 
Restored to an accepted version.

**Comment by tolot27** [comment]
I don't know why the string disappeared but know it came [back](https://crowdin.com/translate/xdrip/7/en-ru?filter=basic&value=0#q=carbs_per_unit) sometime.

**Pull request closed without merging**
